//! Bulk operations for ExitInterview entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateExitInterviewDto;
use crate::application::service::ExitInterviewService;
use crate::domain::entity::ExitInterview;

/// Bulk operation handler for ExitInterview entities.
///
/// Wraps `ExitInterviewService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type ExitInterviewBulkService = GenericBulkService<ExitInterview, CreateExitInterviewDto, ExitInterviewService>;

// <<< CUSTOM
// END CUSTOM
