//! Bulk operations
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod shared_types;
pub use shared_types::*;

pub mod clearance_item_bulk;
pub mod exit_interview_bulk;
pub mod final_settlement_bulk;
pub mod offboarding_bulk;
pub mod onboarding_bulk;
pub mod onboarding_task_bulk;
pub mod promotion_bulk;

pub use clearance_item_bulk::ClearanceItemBulkService;
pub use exit_interview_bulk::ExitInterviewBulkService;
pub use final_settlement_bulk::FinalSettlementBulkService;
pub use offboarding_bulk::OffboardingBulkService;
pub use onboarding_bulk::OnboardingBulkService;
pub use onboarding_task_bulk::OnboardingTaskBulkService;
pub use promotion_bulk::PromotionBulkService;

// <<< CUSTOM
// END CUSTOM
