//! Bulk operations for Offboarding entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOffboardingDto;
use crate::application::service::OffboardingService;
use crate::domain::entity::Offboarding;

/// Bulk operation handler for Offboarding entities.
///
/// Wraps `OffboardingService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OffboardingBulkService = GenericBulkService<Offboarding, CreateOffboardingDto, OffboardingService>;

// <<< CUSTOM
// END CUSTOM
