//! Bulk operations for Onboarding entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateOnboardingDto;
use crate::application::service::OnboardingService;
use crate::domain::entity::Onboarding;

/// Bulk operation handler for Onboarding entities.
///
/// Wraps `OnboardingService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type OnboardingBulkService = GenericBulkService<Onboarding, CreateOnboardingDto, OnboardingService>;

// <<< CUSTOM
// END CUSTOM
