//! ClearanceItem DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ClearanceItem;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ClearanceStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ClearanceItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateClearanceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "clearer_employee_id")]
    pub clearer_employee_id: Option<Uuid>,
    pub status: ClearanceStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ClearanceItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateClearanceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "clearer_employee_id")]
    pub clearer_employee_id: Option<Uuid>,
    pub status: ClearanceStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ClearanceItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchClearanceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "clearer_employee_id")]
    pub clearer_employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ClearanceStatus>,
}

impl PatchClearanceItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.offboarding_id.is_some() || self.title.is_some() || self.clearer_employee_id.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ClearanceItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ClearanceItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub clearer_employee_id: Option<Uuid>,
    pub status: ClearanceStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ClearanceItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ClearanceItemListResponseDto {
    /// List of items
    pub items: Vec<ClearanceItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ClearanceItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ClearanceItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ClearanceItemSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub offboarding_id: Uuid,
    pub title: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ClearanceItem> for ClearanceItemResponseDto {
    fn from(entity: ClearanceItem) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            offboarding_id: entity.offboarding_id,
            title: entity.title,
            clearer_employee_id: entity.clearer_employee_id,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<ClearanceItem> for ClearanceItemSummaryDto {
    fn from(entity: ClearanceItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            offboarding_id: entity.offboarding_id,
            title: entity.title,
            created_at,
        }
    }
}

impl From<CreateClearanceItemDto> for ClearanceItem {
    fn from(dto: CreateClearanceItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            offboarding_id: dto.offboarding_id,
            title: dto.title,
            clearer_employee_id: dto.clearer_employee_id,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ClearanceItem> for ClearanceItemResponseDto {
    fn from(entity: &ClearanceItem) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            offboarding_id: entity.offboarding_id.clone(),
            title: entity.title.clone(),
            clearer_employee_id: entity.clearer_employee_id.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateClearanceItemDto> for ClearanceItem {
    fn from_create_dto(dto: CreateClearanceItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(ClearanceItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateClearanceItemDto> for ClearanceItem {
    fn apply_update(mut self, dto: UpdateClearanceItemDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.offboarding_id = dto.offboarding_id;
        self.title = dto.title;
        self.clearer_employee_id = dto.clearer_employee_id;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ClearanceItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

