//! ContractTemplate DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ContractTemplate;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ContractType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ContractTemplate
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateContractTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "contract_type")]
    pub contract_type: ContractType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "body_template")]
    pub body_template: String,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ContractTemplate
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateContractTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    #[serde(alias = "contract_type")]
    pub contract_type: ContractType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "body_template")]
    pub body_template: String,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ContractTemplate
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchContractTemplateDto {
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "contract_type")]
    pub contract_type: Option<ContractType>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "body_template")]
    pub body_template: Option<String>,
}

impl PatchContractTemplateDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.name.is_some() || self.contract_type.is_some() || self.body_template.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ContractTemplate entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractTemplateResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub name: String,
    pub contract_type: ContractType,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub body_template: String,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ContractTemplate entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractTemplateListResponseDto {
    /// List of items
    pub items: Vec<ContractTemplateResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ContractTemplateListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ContractTemplateResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractTemplateSummaryDto {
    pub id: Uuid,
    pub name: String,
    pub contract_type: ContractType,
    pub body_template: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ContractTemplate> for ContractTemplateResponseDto {
    fn from(entity: ContractTemplate) -> Self {
        Self {
            id: entity.id,
            name: entity.name,
            contract_type: entity.contract_type,
            body_template: entity.body_template,
            metadata: entity.metadata,
        }
    }
}

impl From<ContractTemplate> for ContractTemplateSummaryDto {
    fn from(entity: ContractTemplate) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            name: entity.name,
            contract_type: entity.contract_type,
            body_template: entity.body_template,
            created_at,
        }
    }
}

impl From<CreateContractTemplateDto> for ContractTemplate {
    fn from(dto: CreateContractTemplateDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            name: dto.name,
            contract_type: dto.contract_type,
            body_template: dto.body_template,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ContractTemplate> for ContractTemplateResponseDto {
    fn from(entity: &ContractTemplate) -> Self {
        Self {
            id: entity.id.clone(),
            name: entity.name.clone(),
            contract_type: entity.contract_type.clone(),
            body_template: entity.body_template.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateContractTemplateDto> for ContractTemplate {
    fn from_create_dto(dto: CreateContractTemplateDto) -> backbone_core::ServiceResult<Self> {
        Ok(ContractTemplate::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateContractTemplateDto> for ContractTemplate {
    fn apply_update(mut self, dto: UpdateContractTemplateDto) -> backbone_core::ServiceResult<Self> {
        self.name = dto.name;
        self.contract_type = dto.contract_type;
        self.body_template = dto.body_template;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ContractTemplate here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

