//! Contract DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Contract;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::ContractStatus;
use crate::domain::entity::ContractType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Contract
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateContractDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employment_id")]
    pub employment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "contract_type")]
    pub contract_type: ContractType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "contract_no")]
    pub contract_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "start_date")]
    pub start_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    pub status: ContractStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "previous_contract_id")]
    pub previous_contract_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "cumulative_pkwt_months")]
    pub cumulative_pkwt_months: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reminder_sent_at")]
    pub reminder_sent_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Contract
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateContractDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employment_id")]
    pub employment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "contract_type")]
    pub contract_type: ContractType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "contract_no")]
    pub contract_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "start_date")]
    pub start_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    pub status: ContractStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "previous_contract_id")]
    pub previous_contract_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "cumulative_pkwt_months")]
    pub cumulative_pkwt_months: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "reminder_sent_at")]
    pub reminder_sent_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Contract
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchContractDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employment_id")]
    pub employment_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "contract_type")]
    pub contract_type: Option<ContractType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "contract_no")]
    pub contract_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "start_date")]
    pub start_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "end_date")]
    pub end_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<ContractStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "previous_contract_id")]
    pub previous_contract_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "cumulative_pkwt_months")]
    pub cumulative_pkwt_months: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "reminder_sent_at")]
    pub reminder_sent_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "created_by")]
    pub created_by: Option<Uuid>,
}

impl PatchContractDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employment_id.is_some() || self.employee_id.is_some() || self.contract_type.is_some() || self.contract_no.is_some() || self.start_date.is_some() || self.end_date.is_some() || self.status.is_some() || self.document_file_id.is_some() || self.template_id.is_some() || self.previous_contract_id.is_some() || self.cumulative_pkwt_months.is_some() || self.reminder_sent_at.is_some() || self.created_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Contract entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employment_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub contract_type: ContractType,
    pub contract_no: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub start_date: NaiveDate,
    pub end_date: Option<NaiveDate>,
    pub status: ContractStatus,
    pub document_file_id: Option<Uuid>,
    pub template_id: Option<Uuid>,
    pub previous_contract_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub cumulative_pkwt_months: i32,
    pub reminder_sent_at: Option<DateTime<Utc>>,
    pub created_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Contract entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractListResponseDto {
    /// List of items
    pub items: Vec<ContractResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ContractListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ContractResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ContractSummaryDto {
    pub id: Uuid,
    pub employment_id: Uuid,
    pub employee_id: Uuid,
    pub contract_type: ContractType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Contract> for ContractResponseDto {
    fn from(entity: Contract) -> Self {
        Self {
            id: entity.id,
            employment_id: entity.employment_id,
            employee_id: entity.employee_id,
            contract_type: entity.contract_type,
            contract_no: entity.contract_no,
            start_date: entity.start_date,
            end_date: entity.end_date,
            status: entity.status,
            document_file_id: entity.document_file_id,
            template_id: entity.template_id,
            previous_contract_id: entity.previous_contract_id,
            cumulative_pkwt_months: entity.cumulative_pkwt_months,
            reminder_sent_at: entity.reminder_sent_at,
            created_by: entity.created_by,
            metadata: entity.metadata,
        }
    }
}

impl From<Contract> for ContractSummaryDto {
    fn from(entity: Contract) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employment_id: entity.employment_id,
            employee_id: entity.employee_id,
            contract_type: entity.contract_type,
            created_at,
        }
    }
}

impl From<CreateContractDto> for Contract {
    fn from(dto: CreateContractDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employment_id: dto.employment_id,
            employee_id: dto.employee_id,
            contract_type: dto.contract_type,
            contract_no: dto.contract_no,
            start_date: dto.start_date,
            end_date: dto.end_date,
            status: dto.status,
            document_file_id: dto.document_file_id,
            template_id: dto.template_id,
            previous_contract_id: dto.previous_contract_id,
            cumulative_pkwt_months: dto.cumulative_pkwt_months,
            reminder_sent_at: dto.reminder_sent_at,
            created_by: dto.created_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Contract> for ContractResponseDto {
    fn from(entity: &Contract) -> Self {
        Self {
            id: entity.id.clone(),
            employment_id: entity.employment_id.clone(),
            employee_id: entity.employee_id.clone(),
            contract_type: entity.contract_type.clone(),
            contract_no: entity.contract_no.clone(),
            start_date: entity.start_date.clone(),
            end_date: entity.end_date.clone(),
            status: entity.status.clone(),
            document_file_id: entity.document_file_id.clone(),
            template_id: entity.template_id.clone(),
            previous_contract_id: entity.previous_contract_id.clone(),
            cumulative_pkwt_months: entity.cumulative_pkwt_months.clone(),
            reminder_sent_at: entity.reminder_sent_at.clone(),
            created_by: entity.created_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateContractDto> for Contract {
    fn from_create_dto(dto: CreateContractDto) -> backbone_core::ServiceResult<Self> {
        Ok(Contract::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateContractDto> for Contract {
    fn apply_update(mut self, dto: UpdateContractDto) -> backbone_core::ServiceResult<Self> {
        self.employment_id = dto.employment_id;
        self.employee_id = dto.employee_id;
        self.contract_type = dto.contract_type;
        self.contract_no = dto.contract_no;
        self.start_date = dto.start_date;
        self.end_date = dto.end_date;
        self.status = dto.status;
        self.document_file_id = dto.document_file_id;
        self.template_id = dto.template_id;
        self.previous_contract_id = dto.previous_contract_id;
        self.cumulative_pkwt_months = dto.cumulative_pkwt_months;
        self.reminder_sent_at = dto.reminder_sent_at;
        self.created_by = dto.created_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Contract here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

