//! DisciplineRecord DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::DisciplineRecord;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::DisciplineLevel;
use crate::domain::entity::DisciplineServedDisposition;
use crate::domain::entity::DisciplineStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new DisciplineRecord
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateDisciplineRecordDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    pub level: DisciplineLevel,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub offense: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "issued_at")]
    pub issued_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_until")]
    pub valid_until: DateTime<Utc>,
    #[serde(alias = "served_disposition")]
    pub served_disposition: DisciplineServedDisposition,
    pub status: DisciplineStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_via")]
    pub acknowledged_via: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cancel_reason")]
    pub cancel_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "prior_active_sp1")]
    pub prior_active_sp1: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "prior_active_sp2")]
    pub prior_active_sp2: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "issued_by")]
    pub issued_by: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a DisciplineRecord
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateDisciplineRecordDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    pub level: DisciplineLevel,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub offense: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "issued_at")]
    pub issued_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(alias = "valid_until")]
    pub valid_until: DateTime<Utc>,
    #[serde(alias = "served_disposition")]
    pub served_disposition: DisciplineServedDisposition,
    pub status: DisciplineStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "acknowledged_via")]
    pub acknowledged_via: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "cancel_reason")]
    pub cancel_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "prior_active_sp1")]
    pub prior_active_sp1: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "prior_active_sp2")]
    pub prior_active_sp2: i32,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "issued_by")]
    pub issued_by: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a DisciplineRecord
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchDisciplineRecordDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub level: Option<DisciplineLevel>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub offense: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "issued_at")]
    pub issued_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "valid_until")]
    pub valid_until: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "served_disposition")]
    pub served_disposition: Option<DisciplineServedDisposition>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<DisciplineStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "acknowledged_at")]
    pub acknowledged_at: Option<DateTime<Utc>>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "acknowledged_via")]
    pub acknowledged_via: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "document_file_id")]
    pub document_file_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "cancel_reason")]
    pub cancel_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "prior_active_sp1")]
    pub prior_active_sp1: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "prior_active_sp2")]
    pub prior_active_sp2: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "issued_by")]
    pub issued_by: Option<Uuid>,
}

impl PatchDisciplineRecordDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.level.is_some() || self.offense.is_some() || self.description.is_some() || self.issued_at.is_some() || self.valid_until.is_some() || self.served_disposition.is_some() || self.status.is_some() || self.acknowledged_at.is_some() || self.acknowledged_via.is_some() || self.document_file_id.is_some() || self.cancel_reason.is_some() || self.prior_active_sp1.is_some() || self.prior_active_sp2.is_some() || self.issued_by.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for DisciplineRecord entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DisciplineRecordResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub level: DisciplineLevel,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub offense: String,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub description: String,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub issued_at: DateTime<Utc>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01T00:00:00Z"))]
    pub valid_until: DateTime<Utc>,
    pub served_disposition: DisciplineServedDisposition,
    pub status: DisciplineStatus,
    pub acknowledged_at: Option<DateTime<Utc>>,
    pub acknowledged_via: Option<String>,
    pub document_file_id: Option<Uuid>,
    pub cancel_reason: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub prior_active_sp1: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub prior_active_sp2: i32,
    pub issued_by: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for DisciplineRecord entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DisciplineRecordListResponseDto {
    /// List of items
    pub items: Vec<DisciplineRecordResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl DisciplineRecordListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<DisciplineRecordResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct DisciplineRecordSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub level: DisciplineLevel,
    pub offense: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<DisciplineRecord> for DisciplineRecordResponseDto {
    fn from(entity: DisciplineRecord) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            level: entity.level,
            offense: entity.offense,
            description: entity.description,
            issued_at: entity.issued_at,
            valid_until: entity.valid_until,
            served_disposition: entity.served_disposition,
            status: entity.status,
            acknowledged_at: entity.acknowledged_at,
            acknowledged_via: entity.acknowledged_via,
            document_file_id: entity.document_file_id,
            cancel_reason: entity.cancel_reason,
            prior_active_sp1: entity.prior_active_sp1,
            prior_active_sp2: entity.prior_active_sp2,
            issued_by: entity.issued_by,
            metadata: entity.metadata,
        }
    }
}

impl From<DisciplineRecord> for DisciplineRecordSummaryDto {
    fn from(entity: DisciplineRecord) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            level: entity.level,
            offense: entity.offense,
            created_at,
        }
    }
}

impl From<CreateDisciplineRecordDto> for DisciplineRecord {
    fn from(dto: CreateDisciplineRecordDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            level: dto.level,
            offense: dto.offense,
            description: dto.description,
            issued_at: dto.issued_at,
            valid_until: dto.valid_until,
            served_disposition: dto.served_disposition,
            status: dto.status,
            acknowledged_at: dto.acknowledged_at,
            acknowledged_via: dto.acknowledged_via,
            document_file_id: dto.document_file_id,
            cancel_reason: dto.cancel_reason,
            prior_active_sp1: dto.prior_active_sp1,
            prior_active_sp2: dto.prior_active_sp2,
            issued_by: dto.issued_by,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&DisciplineRecord> for DisciplineRecordResponseDto {
    fn from(entity: &DisciplineRecord) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            level: entity.level.clone(),
            offense: entity.offense.clone(),
            description: entity.description.clone(),
            issued_at: entity.issued_at.clone(),
            valid_until: entity.valid_until.clone(),
            served_disposition: entity.served_disposition.clone(),
            status: entity.status.clone(),
            acknowledged_at: entity.acknowledged_at.clone(),
            acknowledged_via: entity.acknowledged_via.clone(),
            document_file_id: entity.document_file_id.clone(),
            cancel_reason: entity.cancel_reason.clone(),
            prior_active_sp1: entity.prior_active_sp1.clone(),
            prior_active_sp2: entity.prior_active_sp2.clone(),
            issued_by: entity.issued_by.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateDisciplineRecordDto> for DisciplineRecord {
    fn from_create_dto(dto: CreateDisciplineRecordDto) -> backbone_core::ServiceResult<Self> {
        Ok(DisciplineRecord::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateDisciplineRecordDto> for DisciplineRecord {
    fn apply_update(mut self, dto: UpdateDisciplineRecordDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.level = dto.level;
        self.offense = dto.offense;
        self.description = dto.description;
        self.issued_at = dto.issued_at;
        self.valid_until = dto.valid_until;
        self.served_disposition = dto.served_disposition;
        self.status = dto.status;
        self.acknowledged_at = dto.acknowledged_at;
        self.acknowledged_via = dto.acknowledged_via;
        self.document_file_id = dto.document_file_id;
        self.cancel_reason = dto.cancel_reason;
        self.prior_active_sp1 = dto.prior_active_sp1;
        self.prior_active_sp2 = dto.prior_active_sp2;
        self.issued_by = dto.issued_by;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to DisciplineRecord here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

