//! ExitInterview DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::ExitInterview;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new ExitInterview
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateExitInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "conducted_by")]
    pub conducted_by: Option<Uuid>,
    pub responses: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "would_recommend")]
    pub would_recommend: Option<bool>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a ExitInterview
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateExitInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "conducted_by")]
    pub conducted_by: Option<Uuid>,
    pub responses: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "would_recommend")]
    pub would_recommend: Option<bool>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a ExitInterview
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchExitInterviewDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "conducted_by")]
    pub conducted_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub responses: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "would_recommend")]
    pub would_recommend: Option<bool>,
}

impl PatchExitInterviewDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.offboarding_id.is_some() || self.conducted_by.is_some() || self.responses.is_some() || self.would_recommend.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for ExitInterview entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExitInterviewResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub offboarding_id: Option<Uuid>,
    pub conducted_by: Option<Uuid>,
    pub responses: serde_json::Value,
    pub would_recommend: Option<bool>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for ExitInterview entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExitInterviewListResponseDto {
    /// List of items
    pub items: Vec<ExitInterviewResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl ExitInterviewListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<ExitInterviewResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct ExitInterviewSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub offboarding_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<ExitInterview> for ExitInterviewResponseDto {
    fn from(entity: ExitInterview) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            conducted_by: entity.conducted_by,
            responses: entity.responses,
            would_recommend: entity.would_recommend,
            metadata: entity.metadata,
        }
    }
}

impl From<ExitInterview> for ExitInterviewSummaryDto {
    fn from(entity: ExitInterview) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            created_at,
        }
    }
}

impl From<CreateExitInterviewDto> for ExitInterview {
    fn from(dto: CreateExitInterviewDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            offboarding_id: dto.offboarding_id,
            conducted_by: dto.conducted_by,
            responses: dto.responses,
            would_recommend: dto.would_recommend,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&ExitInterview> for ExitInterviewResponseDto {
    fn from(entity: &ExitInterview) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            offboarding_id: entity.offboarding_id.clone(),
            conducted_by: entity.conducted_by.clone(),
            responses: entity.responses.clone(),
            would_recommend: entity.would_recommend.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateExitInterviewDto> for ExitInterview {
    fn from_create_dto(dto: CreateExitInterviewDto) -> backbone_core::ServiceResult<Self> {
        Ok(ExitInterview::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateExitInterviewDto> for ExitInterview {
    fn apply_update(mut self, dto: UpdateExitInterviewDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.offboarding_id = dto.offboarding_id;
        self.conducted_by = dto.conducted_by;
        self.responses = dto.responses;
        self.would_recommend = dto.would_recommend;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to ExitInterview here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

