//! FinalSettlement DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::FinalSettlement;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SettlementStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new FinalSettlement
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    #[serde(alias = "base_pay")]
    pub base_pay: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(alias = "net_payable")]
    pub net_payable: Decimal,
    pub status: SettlementStatus,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a FinalSettlement
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    #[serde(alias = "base_pay")]
    pub base_pay: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(alias = "net_payable")]
    pub net_payable: Decimal,
    pub status: SettlementStatus,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a FinalSettlement
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "base_pay")]
    pub base_pay: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_payable")]
    pub net_payable: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SettlementStatus>,
}

impl PatchFinalSettlementDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.offboarding_id.is_some() || self.period.is_some() || self.base_pay.is_some() || self.unused_leave_payout.is_some() || self.pesangon_amount.is_some() || self.tax_deduction.is_some() || self.net_payable.is_some() || self.status.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for FinalSettlement entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    pub base_pay: Decimal,
    pub unused_leave_payout: Option<Decimal>,
    pub pesangon_amount: Option<Decimal>,
    pub tax_deduction: Option<Decimal>,
    pub net_payable: Decimal,
    pub status: SettlementStatus,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for FinalSettlement entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementListResponseDto {
    /// List of items
    pub items: Vec<FinalSettlementResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl FinalSettlementListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<FinalSettlementResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub offboarding_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<FinalSettlement> for FinalSettlementResponseDto {
    fn from(entity: FinalSettlement) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            period: entity.period,
            base_pay: entity.base_pay,
            unused_leave_payout: entity.unused_leave_payout,
            pesangon_amount: entity.pesangon_amount,
            tax_deduction: entity.tax_deduction,
            net_payable: entity.net_payable,
            status: entity.status,
            metadata: entity.metadata,
        }
    }
}

impl From<FinalSettlement> for FinalSettlementSummaryDto {
    fn from(entity: FinalSettlement) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            created_at,
        }
    }
}

impl From<CreateFinalSettlementDto> for FinalSettlement {
    fn from(dto: CreateFinalSettlementDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            offboarding_id: dto.offboarding_id,
            period: dto.period,
            base_pay: dto.base_pay,
            unused_leave_payout: dto.unused_leave_payout,
            pesangon_amount: dto.pesangon_amount,
            tax_deduction: dto.tax_deduction,
            net_payable: dto.net_payable,
            status: dto.status,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&FinalSettlement> for FinalSettlementResponseDto {
    fn from(entity: &FinalSettlement) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            offboarding_id: entity.offboarding_id.clone(),
            period: entity.period.clone(),
            base_pay: entity.base_pay.clone(),
            unused_leave_payout: entity.unused_leave_payout.clone(),
            pesangon_amount: entity.pesangon_amount.clone(),
            tax_deduction: entity.tax_deduction.clone(),
            net_payable: entity.net_payable.clone(),
            status: entity.status.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateFinalSettlementDto> for FinalSettlement {
    fn from_create_dto(dto: CreateFinalSettlementDto) -> backbone_core::ServiceResult<Self> {
        Ok(FinalSettlement::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateFinalSettlementDto> for FinalSettlement {
    fn apply_update(mut self, dto: UpdateFinalSettlementDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.offboarding_id = dto.offboarding_id;
        self.period = dto.period;
        self.base_pay = dto.base_pay;
        self.unused_leave_payout = dto.unused_leave_payout;
        self.pesangon_amount = dto.pesangon_amount;
        self.tax_deduction = dto.tax_deduction;
        self.net_payable = dto.net_payable;
        self.status = dto.status;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to FinalSettlement here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

