//! FinalSettlement DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::FinalSettlement;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SettlementStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new FinalSettlement
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    #[serde(alias = "base_pay")]
    pub base_pay: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "uang_pesangon")]
    pub uang_pesangon: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upmk: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "uang_pisah")]
    pub uang_pisah: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "monthly_wage")]
    pub monthly_wage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "daily_wage")]
    pub daily_wage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "work_days_per_week")]
    pub work_days_per_week: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_days")]
    pub unused_leave_days: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tenure_years")]
    pub tenure_years: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "legal_basis")]
    pub legal_basis: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "statutory_effective_from")]
    pub statutory_effective_from: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "last_pay_via_payroll")]
    pub last_pay_via_payroll: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(alias = "net_payable")]
    pub net_payable: Decimal,
    pub status: SettlementStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a FinalSettlement
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "offboarding_id")]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    #[serde(alias = "base_pay")]
    pub base_pay: Decimal,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "uang_pesangon")]
    pub uang_pesangon: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub upmk: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "uang_pisah")]
    pub uang_pisah: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "monthly_wage")]
    pub monthly_wage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "daily_wage")]
    pub daily_wage: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "work_days_per_week")]
    pub work_days_per_week: Option<i32>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "unused_leave_days")]
    pub unused_leave_days: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tenure_years")]
    pub tenure_years: Option<Decimal>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "legal_basis")]
    pub legal_basis: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "statutory_effective_from")]
    pub statutory_effective_from: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(alias = "last_pay_via_payroll")]
    pub last_pay_via_payroll: bool,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(alias = "net_payable")]
    pub net_payable: Decimal,
    pub status: SettlementStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a FinalSettlement
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchFinalSettlementDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "offboarding_id")]
    pub offboarding_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub period: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "base_pay")]
    pub base_pay: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unused_leave_payout")]
    pub unused_leave_payout: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "pesangon_amount")]
    pub pesangon_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "uang_pesangon")]
    pub uang_pesangon: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub upmk: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "uang_pisah")]
    pub uang_pisah: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "monthly_wage")]
    pub monthly_wage: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "daily_wage")]
    pub daily_wage: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "work_days_per_week")]
    pub work_days_per_week: Option<i32>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unused_leave_days")]
    pub unused_leave_days: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tenure_years")]
    pub tenure_years: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "legal_basis")]
    pub legal_basis: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "statutory_effective_from")]
    pub statutory_effective_from: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "last_pay_via_payroll")]
    pub last_pay_via_payroll: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_deduction")]
    pub tax_deduction: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "net_payable")]
    pub net_payable: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SettlementStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
}

impl PatchFinalSettlementDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.employee_id.is_some() || self.offboarding_id.is_some() || self.period.is_some() || self.base_pay.is_some() || self.unused_leave_payout.is_some() || self.pesangon_amount.is_some() || self.uang_pesangon.is_some() || self.upmk.is_some() || self.uang_pisah.is_some() || self.monthly_wage.is_some() || self.daily_wage.is_some() || self.work_days_per_week.is_some() || self.unused_leave_days.is_some() || self.tenure_years.is_some() || self.legal_basis.is_some() || self.statutory_effective_from.is_some() || self.last_pay_via_payroll.is_some() || self.tax_deduction.is_some() || self.net_payable.is_some() || self.status.is_some() || self.accounting_post_id.is_some() || self.journal_id.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for FinalSettlement entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub offboarding_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub period: String,
    pub base_pay: Decimal,
    pub unused_leave_payout: Option<Decimal>,
    pub pesangon_amount: Option<Decimal>,
    pub uang_pesangon: Option<Decimal>,
    pub upmk: Option<Decimal>,
    pub uang_pisah: Option<Decimal>,
    pub monthly_wage: Option<Decimal>,
    pub daily_wage: Option<Decimal>,
    pub work_days_per_week: Option<i32>,
    pub unused_leave_days: Option<Decimal>,
    pub tenure_years: Option<Decimal>,
    pub legal_basis: Option<String>,
    pub statutory_effective_from: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = true))]
    pub last_pay_via_payroll: bool,
    pub tax_deduction: Option<Decimal>,
    pub net_payable: Decimal,
    pub status: SettlementStatus,
    pub accounting_post_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for FinalSettlement entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementListResponseDto {
    /// List of items
    pub items: Vec<FinalSettlementResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl FinalSettlementListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<FinalSettlementResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct FinalSettlementSummaryDto {
    pub id: Uuid,
    pub employee_id: Uuid,
    pub offboarding_id: Uuid,
    pub period: String,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<FinalSettlement> for FinalSettlementResponseDto {
    fn from(entity: FinalSettlement) -> Self {
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            period: entity.period,
            base_pay: entity.base_pay,
            unused_leave_payout: entity.unused_leave_payout,
            pesangon_amount: entity.pesangon_amount,
            uang_pesangon: entity.uang_pesangon,
            upmk: entity.upmk,
            uang_pisah: entity.uang_pisah,
            monthly_wage: entity.monthly_wage,
            daily_wage: entity.daily_wage,
            work_days_per_week: entity.work_days_per_week,
            unused_leave_days: entity.unused_leave_days,
            tenure_years: entity.tenure_years,
            legal_basis: entity.legal_basis,
            statutory_effective_from: entity.statutory_effective_from,
            last_pay_via_payroll: entity.last_pay_via_payroll,
            tax_deduction: entity.tax_deduction,
            net_payable: entity.net_payable,
            status: entity.status,
            accounting_post_id: entity.accounting_post_id,
            journal_id: entity.journal_id,
            metadata: entity.metadata,
        }
    }
}

impl From<FinalSettlement> for FinalSettlementSummaryDto {
    fn from(entity: FinalSettlement) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            employee_id: entity.employee_id,
            offboarding_id: entity.offboarding_id,
            period: entity.period,
            created_at,
        }
    }
}

impl From<CreateFinalSettlementDto> for FinalSettlement {
    fn from(dto: CreateFinalSettlementDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            employee_id: dto.employee_id,
            offboarding_id: dto.offboarding_id,
            period: dto.period,
            base_pay: dto.base_pay,
            unused_leave_payout: dto.unused_leave_payout,
            pesangon_amount: dto.pesangon_amount,
            uang_pesangon: dto.uang_pesangon,
            upmk: dto.upmk,
            uang_pisah: dto.uang_pisah,
            monthly_wage: dto.monthly_wage,
            daily_wage: dto.daily_wage,
            work_days_per_week: dto.work_days_per_week,
            unused_leave_days: dto.unused_leave_days,
            tenure_years: dto.tenure_years,
            legal_basis: dto.legal_basis,
            statutory_effective_from: dto.statutory_effective_from,
            last_pay_via_payroll: dto.last_pay_via_payroll,
            tax_deduction: dto.tax_deduction,
            net_payable: dto.net_payable,
            status: dto.status,
            accounting_post_id: dto.accounting_post_id,
            journal_id: dto.journal_id,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&FinalSettlement> for FinalSettlementResponseDto {
    fn from(entity: &FinalSettlement) -> Self {
        Self {
            id: entity.id.clone(),
            employee_id: entity.employee_id.clone(),
            offboarding_id: entity.offboarding_id.clone(),
            period: entity.period.clone(),
            base_pay: entity.base_pay.clone(),
            unused_leave_payout: entity.unused_leave_payout.clone(),
            pesangon_amount: entity.pesangon_amount.clone(),
            uang_pesangon: entity.uang_pesangon.clone(),
            upmk: entity.upmk.clone(),
            uang_pisah: entity.uang_pisah.clone(),
            monthly_wage: entity.monthly_wage.clone(),
            daily_wage: entity.daily_wage.clone(),
            work_days_per_week: entity.work_days_per_week.clone(),
            unused_leave_days: entity.unused_leave_days.clone(),
            tenure_years: entity.tenure_years.clone(),
            legal_basis: entity.legal_basis.clone(),
            statutory_effective_from: entity.statutory_effective_from.clone(),
            last_pay_via_payroll: entity.last_pay_via_payroll.clone(),
            tax_deduction: entity.tax_deduction.clone(),
            net_payable: entity.net_payable.clone(),
            status: entity.status.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            journal_id: entity.journal_id.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateFinalSettlementDto> for FinalSettlement {
    fn from_create_dto(dto: CreateFinalSettlementDto) -> backbone_core::ServiceResult<Self> {
        Ok(FinalSettlement::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateFinalSettlementDto> for FinalSettlement {
    fn apply_update(mut self, dto: UpdateFinalSettlementDto) -> backbone_core::ServiceResult<Self> {
        self.employee_id = dto.employee_id;
        self.offboarding_id = dto.offboarding_id;
        self.period = dto.period;
        self.base_pay = dto.base_pay;
        self.unused_leave_payout = dto.unused_leave_payout;
        self.pesangon_amount = dto.pesangon_amount;
        self.uang_pesangon = dto.uang_pesangon;
        self.upmk = dto.upmk;
        self.uang_pisah = dto.uang_pisah;
        self.monthly_wage = dto.monthly_wage;
        self.daily_wage = dto.daily_wage;
        self.work_days_per_week = dto.work_days_per_week;
        self.unused_leave_days = dto.unused_leave_days;
        self.tenure_years = dto.tenure_years;
        self.legal_basis = dto.legal_basis;
        self.statutory_effective_from = dto.statutory_effective_from;
        self.last_pay_via_payroll = dto.last_pay_via_payroll;
        self.tax_deduction = dto.tax_deduction;
        self.net_payable = dto.net_payable;
        self.status = dto.status;
        self.accounting_post_id = dto.accounting_post_id;
        self.journal_id = dto.journal_id;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to FinalSettlement here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
