//! OnboardingTemplateTask DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::OnboardingTemplateTask;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new OnboardingTemplateTask
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateOnboardingTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "owner_role")]
    pub owner_role: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "due_day_offset")]
    pub due_day_offset: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub ordinal: i32,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a OnboardingTemplateTask
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateOnboardingTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "template_id")]
    pub template_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "owner_role")]
    pub owner_role: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(alias = "due_day_offset")]
    pub due_day_offset: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub ordinal: i32,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a OnboardingTemplateTask
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchOnboardingTemplateTaskDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "template_id")]
    pub template_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "owner_role")]
    pub owner_role: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_day_offset")]
    pub due_day_offset: Option<i32>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub ordinal: Option<i32>,
}

impl PatchOnboardingTemplateTaskDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.template_id.is_some() || self.title.is_some() || self.category.is_some() || self.owner_role.is_some() || self.due_day_offset.is_some() || self.ordinal.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for OnboardingTemplateTask entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OnboardingTemplateTaskResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub template_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub title: String,
    pub category: Option<String>,
    pub owner_role: Option<String>,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub due_day_offset: i32,
    #[cfg_attr(feature = "openapi", schema(example = 42))]
    pub ordinal: i32,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for OnboardingTemplateTask entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OnboardingTemplateTaskListResponseDto {
    /// List of items
    pub items: Vec<OnboardingTemplateTaskResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl OnboardingTemplateTaskListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<OnboardingTemplateTaskResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct OnboardingTemplateTaskSummaryDto {
    pub id: Uuid,
    pub template_id: Uuid,
    pub title: String,
    pub category: Option<String>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<OnboardingTemplateTask> for OnboardingTemplateTaskResponseDto {
    fn from(entity: OnboardingTemplateTask) -> Self {
        Self {
            id: entity.id,
            template_id: entity.template_id,
            title: entity.title,
            category: entity.category,
            owner_role: entity.owner_role,
            due_day_offset: entity.due_day_offset,
            ordinal: entity.ordinal,
            metadata: entity.metadata,
        }
    }
}

impl From<OnboardingTemplateTask> for OnboardingTemplateTaskSummaryDto {
    fn from(entity: OnboardingTemplateTask) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            template_id: entity.template_id,
            title: entity.title,
            category: entity.category,
            created_at,
        }
    }
}

impl From<CreateOnboardingTemplateTaskDto> for OnboardingTemplateTask {
    fn from(dto: CreateOnboardingTemplateTaskDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            template_id: dto.template_id,
            title: dto.title,
            category: dto.category,
            owner_role: dto.owner_role,
            due_day_offset: dto.due_day_offset,
            ordinal: dto.ordinal,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&OnboardingTemplateTask> for OnboardingTemplateTaskResponseDto {
    fn from(entity: &OnboardingTemplateTask) -> Self {
        Self {
            id: entity.id.clone(),
            template_id: entity.template_id.clone(),
            title: entity.title.clone(),
            category: entity.category.clone(),
            owner_role: entity.owner_role.clone(),
            due_day_offset: entity.due_day_offset.clone(),
            ordinal: entity.ordinal.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateOnboardingTemplateTaskDto> for OnboardingTemplateTask {
    fn from_create_dto(dto: CreateOnboardingTemplateTaskDto) -> backbone_core::ServiceResult<Self> {
        Ok(OnboardingTemplateTask::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateOnboardingTemplateTaskDto> for OnboardingTemplateTask {
    fn apply_update(mut self, dto: UpdateOnboardingTemplateTaskDto) -> backbone_core::ServiceResult<Self> {
        self.template_id = dto.template_id;
        self.title = dto.title;
        self.category = dto.category;
        self.owner_role = dto.owner_role;
        self.due_day_offset = dto.due_day_offset;
        self.ordinal = dto.ordinal;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to OnboardingTemplateTask here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

