//! Promotion DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::Promotion;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::PromotionStatus;
use crate::domain::entity::PromotionType;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new Promotion
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreatePromotionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "promotion_type")]
    pub promotion_type: PromotionType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_date")]
    pub effective_date: NaiveDate,
    pub status: PromotionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "requested_by")]
    pub requested_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "appraisal_id")]
    pub appraisal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a Promotion
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdatePromotionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "employee_id")]
    pub employee_id: Uuid,
    #[serde(alias = "promotion_type")]
    pub promotion_type: PromotionType,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "effective_date")]
    pub effective_date: NaiveDate,
    pub status: PromotionStatus,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "requested_by")]
    pub requested_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "appraisal_id")]
    pub appraisal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a Promotion
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchPromotionDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "employee_id")]
    pub employee_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "promotion_type")]
    pub promotion_type: Option<PromotionType>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id_from")]
    pub position_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "position_id_to")]
    pub position_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "level_id_from")]
    pub level_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "level_id_to")]
    pub level_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id_from")]
    pub department_id_from: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "department_id_to")]
    pub department_id_to: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "proposed_salary")]
    pub proposed_salary: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "effective_date")]
    pub effective_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<PromotionStatus>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "requested_by")]
    pub requested_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "approved_by")]
    pub approved_by: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "appraisal_id")]
    pub appraisal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

impl PatchPromotionDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.promotion_type.is_some() || self.position_id_from.is_some() || self.position_id_to.is_some() || self.level_id_from.is_some() || self.level_id_to.is_some() || self.department_id_from.is_some() || self.department_id_to.is_some() || self.proposed_salary.is_some() || self.effective_date.is_some() || self.status.is_some() || self.requested_by.is_some() || self.approved_by.is_some() || self.appraisal_id.is_some() || self.reason.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for Promotion entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromotionResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub employee_id: Uuid,
    pub promotion_type: PromotionType,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub proposed_salary: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub effective_date: NaiveDate,
    pub status: PromotionStatus,
    pub requested_by: Option<Uuid>,
    pub approved_by: Option<Uuid>,
    pub appraisal_id: Option<Uuid>,
    pub reason: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for Promotion entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromotionListResponseDto {
    /// List of items
    pub items: Vec<PromotionResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl PromotionListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<PromotionResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct PromotionSummaryDto {
    pub id: Uuid,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub promotion_type: PromotionType,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<Promotion> for PromotionResponseDto {
    fn from(entity: Promotion) -> Self {
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            promotion_type: entity.promotion_type,
            position_id_from: entity.position_id_from,
            position_id_to: entity.position_id_to,
            level_id_from: entity.level_id_from,
            level_id_to: entity.level_id_to,
            department_id_from: entity.department_id_from,
            department_id_to: entity.department_id_to,
            proposed_salary: entity.proposed_salary,
            effective_date: entity.effective_date,
            status: entity.status,
            requested_by: entity.requested_by,
            approved_by: entity.approved_by,
            appraisal_id: entity.appraisal_id,
            reason: entity.reason,
            metadata: entity.metadata,
        }
    }
}

impl From<Promotion> for PromotionSummaryDto {
    fn from(entity: Promotion) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            company_id: entity.company_id,
            employee_id: entity.employee_id,
            promotion_type: entity.promotion_type,
            created_at,
        }
    }
}

impl From<CreatePromotionDto> for Promotion {
    fn from(dto: CreatePromotionDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            company_id: dto.company_id,
            employee_id: dto.employee_id,
            promotion_type: dto.promotion_type,
            position_id_from: dto.position_id_from,
            position_id_to: dto.position_id_to,
            level_id_from: dto.level_id_from,
            level_id_to: dto.level_id_to,
            department_id_from: dto.department_id_from,
            department_id_to: dto.department_id_to,
            proposed_salary: dto.proposed_salary,
            effective_date: dto.effective_date,
            status: dto.status,
            requested_by: dto.requested_by,
            approved_by: dto.approved_by,
            appraisal_id: dto.appraisal_id,
            reason: dto.reason,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&Promotion> for PromotionResponseDto {
    fn from(entity: &Promotion) -> Self {
        Self {
            id: entity.id.clone(),
            company_id: entity.company_id.clone(),
            employee_id: entity.employee_id.clone(),
            promotion_type: entity.promotion_type.clone(),
            position_id_from: entity.position_id_from.clone(),
            position_id_to: entity.position_id_to.clone(),
            level_id_from: entity.level_id_from.clone(),
            level_id_to: entity.level_id_to.clone(),
            department_id_from: entity.department_id_from.clone(),
            department_id_to: entity.department_id_to.clone(),
            proposed_salary: entity.proposed_salary.clone(),
            effective_date: entity.effective_date.clone(),
            status: entity.status.clone(),
            requested_by: entity.requested_by.clone(),
            approved_by: entity.approved_by.clone(),
            appraisal_id: entity.appraisal_id.clone(),
            reason: entity.reason.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreatePromotionDto> for Promotion {
    fn from_create_dto(dto: CreatePromotionDto) -> backbone_core::ServiceResult<Self> {
        Ok(Promotion::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdatePromotionDto> for Promotion {
    fn apply_update(mut self, dto: UpdatePromotionDto) -> backbone_core::ServiceResult<Self> {
        self.company_id = dto.company_id;
        self.employee_id = dto.employee_id;
        self.promotion_type = dto.promotion_type;
        self.position_id_from = dto.position_id_from;
        self.position_id_to = dto.position_id_to;
        self.level_id_from = dto.level_id_from;
        self.level_id_to = dto.level_id_to;
        self.department_id_from = dto.department_id_from;
        self.department_id_to = dto.department_id_to;
        self.proposed_salary = dto.proposed_salary;
        self.effective_date = dto.effective_date;
        self.status = dto.status;
        self.requested_by = dto.requested_by;
        self.approved_by = dto.approved_by;
        self.appraisal_id = dto.appraisal_id;
        self.reason = dto.reason;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to Promotion here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs

