//! Domain policy for Promotion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::Promotion;

/// Domain policy for Promotion — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<Promotion>` in the `// <<< CUSTOM` zone.
pub type PromotionDomainPolicy = PermitAllPolicy<Promotion>;

// <<< CUSTOM
// END CUSTOM
