//! Application service for ClearanceItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `clearance_item_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateClearanceItemDto, UpdateClearanceItemDto};
use crate::domain::entity::ClearanceItem;
use crate::infrastructure::persistence::ClearanceItemRepository;

/// Application service for ClearanceItem entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `clearance_item_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ClearanceItemServiceCustom {
///     inner: Arc<ClearanceItemService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ClearanceItemService = GenericCrudService<
    ClearanceItem,
    CreateClearanceItemDto,
    UpdateClearanceItemDto,
    ClearanceItemRepository,
>;

// <<< CUSTOM
// END CUSTOM
