//! Application service for ContractTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `contract_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateContractTemplateDto, UpdateContractTemplateDto};
use crate::domain::entity::ContractTemplate;
use crate::infrastructure::persistence::ContractTemplateRepository;

/// Application service for ContractTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `contract_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct ContractTemplateServiceCustom {
///     inner: Arc<ContractTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type ContractTemplateService = GenericCrudService<
    ContractTemplate,
    CreateContractTemplateDto,
    UpdateContractTemplateDto,
    ContractTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
