//! Application service for DisciplineRecord entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `discipline_record_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateDisciplineRecordDto, UpdateDisciplineRecordDto};
use crate::domain::entity::DisciplineRecord;
use crate::infrastructure::persistence::DisciplineRecordRepository;

/// Application service for DisciplineRecord entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `discipline_record_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct DisciplineRecordServiceCustom {
///     inner: Arc<DisciplineRecordService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type DisciplineRecordService = GenericCrudService<
    DisciplineRecord,
    CreateDisciplineRecordDto,
    UpdateDisciplineRecordDto,
    DisciplineRecordRepository,
>;

// <<< CUSTOM
// END CUSTOM
