//! Application service for FinalSettlement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `final_settlement_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateFinalSettlementDto, UpdateFinalSettlementDto};
use crate::domain::entity::FinalSettlement;
use crate::infrastructure::persistence::FinalSettlementRepository;

/// Application service for FinalSettlement entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `final_settlement_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct FinalSettlementServiceCustom {
///     inner: Arc<FinalSettlementService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type FinalSettlementService = GenericCrudService<
    FinalSettlement,
    CreateFinalSettlementDto,
    UpdateFinalSettlementDto,
    FinalSettlementRepository,
>;

// <<< CUSTOM
// END CUSTOM
