//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod clearance_item_service;
pub mod exit_interview_service;
pub mod final_settlement_service;
pub mod offboarding_service;
pub mod onboarding_service;
pub mod onboarding_task_service;
pub mod onboarding_template_service;
pub mod onboarding_template_task_service;
pub mod promotion_service;
// The three employment-record entities: generated CRUD services (the write
// verbs live in their dedicated write services below).
pub mod contract_service;
pub mod contract_template_service;
pub mod discipline_record_service;
pub use contract_service::ContractService;
pub use contract_template_service::ContractTemplateService;
pub use discipline_record_service::DisciplineRecordService;

// <<< CUSTOM
pub mod pesangon;
// ADR-005 producers: the three career-lifecycle compound events. Each stages an outbox row in-tx
// with its state change (approved→effective / in_progress→completed / cleared→closed). User-owned
// custom files — never regenerated.
pub mod promotion_write_service;
pub mod promotion_approvals_port;
pub mod onboarding_write_service;
pub mod offboarding_write_service;
// The cross-module read ports the offboarding producer needs to compute the 🇮🇩 pesangon at close
// time (join_date / current salary / remaining leave). Trait seam + pool-backed default impl.
pub mod offboarding_ports;
// Outbound activity-scheduling port: put a mail activity on a checkpoint owner's plate without a
// Cargo edge into the mail domain. The host app wires the adapter; the unwired default fails
// closed on any explicit notify request.
pub mod activity_port;
// Checkpoint create verbs (onboarding tasks / clearance items) with the optional notify side
// effect — fail-closed pre-check, insert, commit, schedule after commit.
pub mod checkpoint_write_service;
// Final-settlement draft (idempotent, one per offboarding) + GL confirmation through the shared
// backbone-gl-posting port (stamp only after accounting acks; unwired default = loud 422).
pub mod final_settlement_write_service;
// Discipline records (SP1-SP3): valid on service, expiry derived, the
// employee's contest through the optional approvals port.
pub mod discipline_write_service;
pub mod discipline_events;
// Employment contracts (PKWT/PKWTT): the decision verb through the approvals
// port, the reminder tick, and the expiry events.
pub mod contract_write_service;
pub mod contract_events;
// The exit-started and task-assigned events (#558's remaining arms).
pub mod lifecycle_events;
// END CUSTOM

pub use clearance_item_service::ClearanceItemService;
pub use exit_interview_service::ExitInterviewService;
pub use final_settlement_service::FinalSettlementService;
pub use offboarding_service::OffboardingService;
pub use onboarding_service::OnboardingService;
pub use onboarding_task_service::OnboardingTaskService;
pub use onboarding_template_service::OnboardingTemplateService;
pub use onboarding_template_task_service::OnboardingTemplateTaskService;
pub use promotion_service::PromotionService;
// <<< CUSTOM
pub use pesangon::{
    pesangon, PesangonBreakdown, PesangonConfig, PesangonError, ReasonRule, UpmkScaleStep,
};
pub use promotion_write_service::{
    PromotionValidationPort,
    NewPromotion, PromotionEffectError, PromotionWriteService, PROMOTION_EFFECTIVE_EVENT_TYPE,
};
pub use onboarding_write_service::{
    NewOnboarding, OnboardingCompleteError, OnboardingWriteService, ONBOARDING_COMPLETED_EVENT_TYPE,
    PROBATION_CONFIRMED_EVENT_TYPE,
};
pub use offboarding_write_service::{
    NewOffboarding, OffboardingCloseError, OffboardingWriteService, OFFBOARDING_CLOSED_EVENT_TYPE,
};
pub use offboarding_ports::{OffboardingInputs, PoolOffboardingInputs};
pub use activity_port::{ActivityAck, ActivityCommand, ActivityRejected, ActivitySink, UnwiredActivitySink};
pub use checkpoint_write_service::{
    ClearanceItemWriteService, CheckpointError, NewClearanceItem, NewOnboardingTask,
    OnboardingTaskWriteService,
};
pub use final_settlement_write_service::{
    FinalSettlementError, FinalSettlementWriteService, SettlementAccounts, UnwiredGlSink,
};
pub use discipline_write_service::{
    ContestFiling, DisciplineApprovalsPort, DisciplineError, DisciplineWriteService,
    NewDisciplineRecord, ACTIVE_PREDICATE,
};
pub use discipline_events::{DisciplineEvent, DisciplineEventSink, LoggingSink as DisciplineLoggingSink};
pub use contract_write_service::{
    ContractApprovalsPort, ContractDecision, ContractDecisionFiling, ContractError,
    ContractWriteService, NewContract, PKWT_CAP_MONTHS,
};
pub use contract_events::{ContractEvent, ContractEventSink, LoggingSink as ContractLoggingSink};
pub use lifecycle_events::{LifecycleEvent, LifecycleEventSink, LoggingSink as LifecycleLoggingSink};
// END CUSTOM
