//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod clearance_item_service;
pub mod exit_interview_service;
pub mod final_settlement_service;
pub mod offboarding_service;
pub mod onboarding_service;
pub mod onboarding_task_service;
pub mod promotion_service;

// <<< CUSTOM
pub mod pesangon;
// ADR-005 producers: the three career-lifecycle compound events. Each stages an outbox row in-tx
// with its state change (approved→effective / in_progress→completed / cleared→closed). User-owned
// custom files — never regenerated.
pub mod promotion_write_service;
pub mod onboarding_write_service;
pub mod offboarding_write_service;
// The cross-module read ports the offboarding producer needs to compute the 🇮🇩 pesangon at close
// time (join_date / current salary / remaining leave). Trait seam + pool-backed default impl.
pub mod offboarding_ports;
// END CUSTOM

pub use clearance_item_service::ClearanceItemService;
pub use exit_interview_service::ExitInterviewService;
pub use final_settlement_service::FinalSettlementService;
pub use offboarding_service::OffboardingService;
pub use onboarding_service::OnboardingService;
pub use onboarding_task_service::OnboardingTaskService;
pub use promotion_service::PromotionService;
// <<< CUSTOM
pub use pesangon::{
    pesangon, PesangonBreakdown, PesangonConfig, PesangonError, ReasonRule, UpmkScaleStep,
};
pub use promotion_write_service::{
    PromotionEffectError, PromotionWriteService, PROMOTION_EFFECTIVE_EVENT_TYPE,
};
pub use onboarding_write_service::{
    OnboardingCompleteError, OnboardingWriteService, ONBOARDING_COMPLETED_EVENT_TYPE,
};
pub use offboarding_write_service::{
    OffboardingCloseError, OffboardingWriteService, OFFBOARDING_CLOSED_EVENT_TYPE,
};
pub use offboarding_ports::{OffboardingInputs, PoolOffboardingInputs};
// END CUSTOM
