//! Application service for Offboarding entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `offboarding_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOffboardingDto, UpdateOffboardingDto};
use crate::domain::entity::Offboarding;
use crate::infrastructure::persistence::OffboardingRepository;

/// Application service for Offboarding entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `offboarding_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OffboardingServiceCustom {
///     inner: Arc<OffboardingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OffboardingService = GenericCrudService<
    Offboarding,
    CreateOffboardingDto,
    UpdateOffboardingDto,
    OffboardingRepository,
>;

// <<< CUSTOM
// END CUSTOM
