//! Application service for OnboardingTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `onboarding_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOnboardingTemplateDto, UpdateOnboardingTemplateDto};
use crate::domain::entity::OnboardingTemplate;
use crate::infrastructure::persistence::OnboardingTemplateRepository;

/// Application service for OnboardingTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `onboarding_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OnboardingTemplateServiceCustom {
///     inner: Arc<OnboardingTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OnboardingTemplateService = GenericCrudService<
    OnboardingTemplate,
    CreateOnboardingTemplateDto,
    UpdateOnboardingTemplateDto,
    OnboardingTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
