//! Application service for Onboarding entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `onboarding_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOnboardingDto, UpdateOnboardingDto};
use crate::domain::entity::Onboarding;
use crate::infrastructure::persistence::OnboardingRepository;

/// Application service for Onboarding entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `onboarding_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OnboardingServiceCustom {
///     inner: Arc<OnboardingService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OnboardingService = GenericCrudService<
    Onboarding,
    CreateOnboardingDto,
    UpdateOnboardingDto,
    OnboardingRepository,
>;

// <<< CUSTOM
// END CUSTOM
