//! Application service for OnboardingTemplateTask entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `onboarding_template_task_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateOnboardingTemplateTaskDto, UpdateOnboardingTemplateTaskDto};
use crate::domain::entity::OnboardingTemplateTask;
use crate::infrastructure::persistence::OnboardingTemplateTaskRepository;

/// Application service for OnboardingTemplateTask entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `onboarding_template_task_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct OnboardingTemplateTaskServiceCustom {
///     inner: Arc<OnboardingTemplateTaskService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type OnboardingTemplateTaskService = GenericCrudService<
    OnboardingTemplateTask,
    CreateOnboardingTemplateTaskDto,
    UpdateOnboardingTemplateTaskDto,
    OnboardingTemplateTaskRepository,
>;

// <<< CUSTOM
// END CUSTOM
