-- Contract Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.contracts table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.contracts (
--     id,
--     employment_id,
--     employee_id,
--     contract_type,
--     contract_no,
--     start_date,
--     end_date,
--     status,
--     document_file_id,
--     template_id,
--     previous_contract_id,
--     cumulative_pkwt_months,
--     reminder_sent_at,
--     created_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.contracts (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

