-- DisciplineRecord Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.discipline_records table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.discipline_records (
--     id,
--     employee_id,
--     level,
--     offense,
--     description,
--     issued_at,
--     valid_until,
--     served_disposition,
--     status,
--     acknowledged_at,
--     acknowledged_via,
--     document_file_id,
--     cancel_reason,
--     prior_active_sp1,
--     prior_active_sp2,
--     issued_by,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.discipline_records (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

