-- ExitInterview Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.exit_interviews table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.exit_interviews (
--     id,
--     company_id,
--     employee_id,
--     offboarding_id,
--     conducted_by,
--     responses,
--     would_recommend,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.exit_interviews (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

