-- FinalSettlement Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.final_settlements table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.final_settlements (
--     id,
--     company_id,
--     employee_id,
--     offboarding_id,
--     period,
--     base_pay,
--     unused_leave_payout,
--     pesangon_amount,
--     tax_deduction,
--     net_payable,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.final_settlements (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

