-- Onboarding Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.onboardings table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.onboardings (
--     id,
--     company_id,
--     employee_id,
--     start_date,
--     status,
--     completed_at,
--     template_id,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.onboardings (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

