-- OnboardingTask Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.onboarding_tasks table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.onboarding_tasks (
--     id,
--     company_id,
--     onboarding_id,
--     title,
--     category,
--     owner_employee_id,
--     due_date,
--     status,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.onboarding_tasks (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

