-- Promotion Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the lifecycle.promotions table.
-- Customize this file to add your initial data.

-- INSERT INTO lifecycle.promotions (
--     id,
--     company_id,
--     employee_id,
--     promotion_type,
--     position_id_from,
--     position_id_to,
--     level_id_from,
--     level_id_to,
--     department_id_from,
--     department_id_to,
--     proposed_salary,
--     effective_date,
--     status,
--     requested_by,
--     approved_by,
--     appraisal_id,
--     reason,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO lifecycle.promotions (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

