-- Data-change audit capture for DisciplineRecord (@audited, ADR-0025).
-- Generated by metaphor-schema
--
-- Row-level AFTER trigger calling the composed backbone-auditlog
-- module's shared capture function, with the primary-key column
-- name as the single trigger argument. One audit row per affected
-- row, in the same transaction as the write. Requires
-- backbone-auditlog composed (its migrations own the trail table
-- and the capture function this trigger calls).

DROP TRIGGER IF EXISTS discipline_records_data_change_audit ON lifecycle.discipline_records;

CREATE TRIGGER discipline_records_data_change_audit
    AFTER INSERT OR UPDATE OR DELETE ON lifecycle.discipline_records
    FOR EACH ROW EXECUTE FUNCTION auditlog.capture_data_change('id');
