-- Migration: Create final_settlements table
-- Generated by metaphor-schema

-- Create settlement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_status') THEN
        CREATE TYPE settlement_status AS ENUM ('draft', 'confirmed', 'paid', 'disputed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS lifecycle;

CREATE TABLE IF NOT EXISTS lifecycle.final_settlements (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    offboarding_id UUID NOT NULL,
    period TEXT NOT NULL,
    base_pay NUMERIC(18, 2) NOT NULL CHECK (base_pay >= 0),
    unused_leave_payout NUMERIC(18, 2) CHECK (unused_leave_payout >= 0),
    pesangon_amount NUMERIC(18, 2) CHECK (pesangon_amount >= 0),
    tax_deduction NUMERIC(18, 2) CHECK (tax_deduction >= 0),
    net_payable NUMERIC(18, 2) NOT NULL,
    status settlement_status NOT NULL DEFAULT 'draft',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_final_settlements_company_id ON lifecycle.final_settlements (company_id);

CREATE INDEX IF NOT EXISTS idx_final_settlements_company_id_employee_id ON lifecycle.final_settlements (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_final_settlements_offboarding_id ON lifecycle.final_settlements (offboarding_id);

CREATE INDEX IF NOT EXISTS idx_final_settlements_status ON lifecycle.final_settlements (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_final_settlements_metadata_gin ON lifecycle.final_settlements USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_final_settlements_metadata_deleted_at ON lifecycle.final_settlements ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_final_settlements_metadata_created_at ON lifecycle.final_settlements ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_final_settlements_metadata_updated_at ON lifecycle.final_settlements ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lifecycle.final_settlements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS final_settlements_insert_audit ON lifecycle.final_settlements;
CREATE TRIGGER final_settlements_insert_audit BEFORE INSERT ON lifecycle.final_settlements
    FOR EACH ROW EXECUTE FUNCTION lifecycle.final_settlements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS final_settlements_update_audit ON lifecycle.final_settlements;
CREATE TRIGGER final_settlements_update_audit BEFORE UPDATE ON lifecycle.final_settlements
    FOR EACH ROW EXECUTE FUNCTION lifecycle.final_settlements_audit_timestamp();
