-- Enum types for lifecycle module
-- Generated by metaphor-schema

-- Create clearance_status enum type
-- The schema must exist before a type can be created inside it. This
-- migration now qualifies its enums to `lifecycle`, so it owns bringing the
-- schema up rather than depending on a later table migration to do it.
CREATE SCHEMA IF NOT EXISTS lifecycle;

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'clearance_status') THEN
        CREATE TYPE clearance_status AS ENUM ('pending', 'cleared', 'blocked');
    END IF;
END
$$;

-- Create settlement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_status') THEN
        CREATE TYPE settlement_status AS ENUM ('draft', 'confirmed', 'paid', 'disputed');
    END IF;
END
$$;

-- Create offboarding_reason enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offboarding_reason') THEN
        CREATE TYPE offboarding_reason AS ENUM ('resignation', 'termination', 'end_of_contract', 'retirement', 'death', 'merger_acquisition', 'efficiency', 'force_majeure', 'misconduct');
    END IF;
END
$$;

-- Create offboarding_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offboarding_status') THEN
        CREATE TYPE offboarding_status AS ENUM ('initiated', 'in_progress', 'cleared', 'closed');
    END IF;
END
$$;

-- Create onboarding_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'onboarding_status') THEN
        CREATE TYPE onboarding_status AS ENUM ('pending', 'in_progress', 'completed', 'abandoned');
    END IF;
END
$$;

-- Create task_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_category') THEN
        CREATE TYPE task_category AS ENUM ('document', 'equipment', 'account_access', 'policy_ack', 'induction');
    END IF;
END
$$;

-- Create task_status enum type
-- `task_status` is NOT a shared vocabulary. This module's task states and the
-- ones another module happens to give the same name are different concepts with
-- disjoint values, so the type is qualified to this module's own schema. An
-- unqualified CREATE TYPE lands in whichever schema the search_path names and
-- the guard below matched the name in ANY schema, so whichever module migrated
-- first won globally and the other's columns failed on a value the type it
-- found does not have.
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t JOIN pg_namespace n ON n.oid = t.typnamespace
                   WHERE t.typname = 'task_status' AND n.nspname = 'lifecycle') THEN
        CREATE TYPE lifecycle.task_status AS ENUM ('pending', 'done', 'skipped', 'blocked');
    END IF;
END
$$;

-- Create promotion_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_type') THEN
        CREATE TYPE promotion_type AS ENUM ('promotion', 'transfer', 'demotion', 'lateral');
    END IF;
END
$$;

-- Create promotion_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_status') THEN
        CREATE TYPE promotion_status AS ENUM ('draft', 'pending', 'approved', 'rejected', 'effective', 'cancelled');
    END IF;
END
$$;

