-- Audit Triggers Migration for lifecycle module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: ClearanceItem (lifecycle.clearance_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.clearance_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS clearance_items_insert_audit ON lifecycle.clearance_items;
CREATE TRIGGER clearance_items_insert_audit BEFORE INSERT ON lifecycle.clearance_items
    FOR EACH ROW EXECUTE FUNCTION lifecycle.clearance_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS clearance_items_update_audit ON lifecycle.clearance_items;
CREATE TRIGGER clearance_items_update_audit BEFORE UPDATE ON lifecycle.clearance_items
    FOR EACH ROW EXECUTE FUNCTION lifecycle.clearance_items_audit_timestamp();

-- ==============================================================================
-- Table: ExitInterview (lifecycle.exit_interviews)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.exit_interviews_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS exit_interviews_insert_audit ON lifecycle.exit_interviews;
CREATE TRIGGER exit_interviews_insert_audit BEFORE INSERT ON lifecycle.exit_interviews
    FOR EACH ROW EXECUTE FUNCTION lifecycle.exit_interviews_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS exit_interviews_update_audit ON lifecycle.exit_interviews;
CREATE TRIGGER exit_interviews_update_audit BEFORE UPDATE ON lifecycle.exit_interviews
    FOR EACH ROW EXECUTE FUNCTION lifecycle.exit_interviews_audit_timestamp();

-- ==============================================================================
-- Table: FinalSettlement (lifecycle.final_settlements)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.final_settlements_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS final_settlements_insert_audit ON lifecycle.final_settlements;
CREATE TRIGGER final_settlements_insert_audit BEFORE INSERT ON lifecycle.final_settlements
    FOR EACH ROW EXECUTE FUNCTION lifecycle.final_settlements_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS final_settlements_update_audit ON lifecycle.final_settlements;
CREATE TRIGGER final_settlements_update_audit BEFORE UPDATE ON lifecycle.final_settlements
    FOR EACH ROW EXECUTE FUNCTION lifecycle.final_settlements_audit_timestamp();

-- ==============================================================================
-- Table: Offboarding (lifecycle.offboardings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.offboardings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS offboardings_insert_audit ON lifecycle.offboardings;
CREATE TRIGGER offboardings_insert_audit BEFORE INSERT ON lifecycle.offboardings
    FOR EACH ROW EXECUTE FUNCTION lifecycle.offboardings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS offboardings_update_audit ON lifecycle.offboardings;
CREATE TRIGGER offboardings_update_audit BEFORE UPDATE ON lifecycle.offboardings
    FOR EACH ROW EXECUTE FUNCTION lifecycle.offboardings_audit_timestamp();

-- ==============================================================================
-- Table: Onboarding (lifecycle.onboardings)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.onboardings_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS onboardings_insert_audit ON lifecycle.onboardings;
CREATE TRIGGER onboardings_insert_audit BEFORE INSERT ON lifecycle.onboardings
    FOR EACH ROW EXECUTE FUNCTION lifecycle.onboardings_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS onboardings_update_audit ON lifecycle.onboardings;
CREATE TRIGGER onboardings_update_audit BEFORE UPDATE ON lifecycle.onboardings
    FOR EACH ROW EXECUTE FUNCTION lifecycle.onboardings_audit_timestamp();

-- ==============================================================================
-- Table: OnboardingTask (lifecycle.onboarding_tasks)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.onboarding_tasks_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS onboarding_tasks_insert_audit ON lifecycle.onboarding_tasks;
CREATE TRIGGER onboarding_tasks_insert_audit BEFORE INSERT ON lifecycle.onboarding_tasks
    FOR EACH ROW EXECUTE FUNCTION lifecycle.onboarding_tasks_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS onboarding_tasks_update_audit ON lifecycle.onboarding_tasks;
CREATE TRIGGER onboarding_tasks_update_audit BEFORE UPDATE ON lifecycle.onboarding_tasks
    FOR EACH ROW EXECUTE FUNCTION lifecycle.onboarding_tasks_audit_timestamp();

-- ==============================================================================
-- Table: Promotion (lifecycle.promotions)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION lifecycle.promotions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS promotions_insert_audit ON lifecycle.promotions;
CREATE TRIGGER promotions_insert_audit BEFORE INSERT ON lifecycle.promotions
    FOR EACH ROW EXECUTE FUNCTION lifecycle.promotions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS promotions_update_audit ON lifecycle.promotions;
CREATE TRIGGER promotions_update_audit BEFORE UPDATE ON lifecycle.promotions
    FOR EACH ROW EXECUTE FUNCTION lifecycle.promotions_audit_timestamp();

