-- Revert the ADR-0014 strict company fence for lifecycle module (Wave 1 P0 sweep).
-- Generated by metaphor-schema.
DROP POLICY IF EXISTS clearance_items_company_isolation ON lifecycle.clearance_items;
ALTER TABLE lifecycle.clearance_items NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.clearance_items DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS exit_interviews_company_isolation ON lifecycle.exit_interviews;
ALTER TABLE lifecycle.exit_interviews NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.exit_interviews DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS final_settlements_company_isolation ON lifecycle.final_settlements;
ALTER TABLE lifecycle.final_settlements NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.final_settlements DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS offboardings_company_isolation ON lifecycle.offboardings;
ALTER TABLE lifecycle.offboardings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.offboardings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS onboarding_tasks_company_isolation ON lifecycle.onboarding_tasks;
ALTER TABLE lifecycle.onboarding_tasks NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.onboarding_tasks DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS onboardings_company_isolation ON lifecycle.onboardings;
ALTER TABLE lifecycle.onboardings NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.onboardings DISABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promotions_company_isolation ON lifecycle.promotions;
ALTER TABLE lifecycle.promotions NO FORCE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.promotions DISABLE ROW LEVEL SECURITY;
