-- Company RLS fence for lifecycle module (ADR-0008)
-- Generated by metaphor-schema. Requires the app to connect as a
-- non-superuser role; migrations/seeders run as the owner and bypass.

-- Migration: company row-level-security fence for lifecycle.clearance_items
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.clearance_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.clearance_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS clearance_items_company_isolation ON lifecycle.clearance_items;
CREATE POLICY clearance_items_company_isolation ON lifecycle.clearance_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.exit_interviews
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.exit_interviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.exit_interviews FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS exit_interviews_company_isolation ON lifecycle.exit_interviews;
CREATE POLICY exit_interviews_company_isolation ON lifecycle.exit_interviews
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.final_settlements
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.final_settlements ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.final_settlements FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS final_settlements_company_isolation ON lifecycle.final_settlements;
CREATE POLICY final_settlements_company_isolation ON lifecycle.final_settlements
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.offboardings
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.offboardings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.offboardings FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS offboardings_company_isolation ON lifecycle.offboardings;
CREATE POLICY offboardings_company_isolation ON lifecycle.offboardings
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.onboardings
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.onboardings ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.onboardings FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS onboardings_company_isolation ON lifecycle.onboardings;
CREATE POLICY onboardings_company_isolation ON lifecycle.onboardings
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.onboarding_tasks
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.onboarding_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.onboarding_tasks FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS onboarding_tasks_company_isolation ON lifecycle.onboarding_tasks;
CREATE POLICY onboarding_tasks_company_isolation ON lifecycle.onboarding_tasks
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

-- Migration: company row-level-security fence for lifecycle.promotions
-- Generated by metaphor-schema (ADR-0008). company_id is scoped per request
-- via `set_config('app.company_id', <uuid>, true)`; an unset var sees zero rows.

ALTER TABLE lifecycle.promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE lifecycle.promotions FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS promotions_company_isolation ON lifecycle.promotions;
CREATE POLICY promotions_company_isolation ON lifecycle.promotions
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

