-- Migration: Create contracts table
-- Generated by metaphor-schema

-- Create contract_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'contract_type') THEN
        CREATE TYPE contract_type AS ENUM ('pkwtt', 'pkwt');
    END IF;
END
$$;

-- Create contract_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'contract_status') THEN
        CREATE TYPE contract_status AS ENUM ('active', 'decision_pending', 'superseded', 'ended');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS lifecycle;

CREATE TABLE IF NOT EXISTS lifecycle.contracts (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    employment_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    contract_type contract_type NOT NULL,
    contract_no TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    status contract_status NOT NULL DEFAULT 'active',
    document_file_id UUID,
    template_id UUID,
    previous_contract_id UUID,
    cumulative_pkwt_months INTEGER NOT NULL DEFAULT 0,
    reminder_sent_at TIMESTAMPTZ,
    created_by UUID,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_contracts_employment_id ON lifecycle.contracts (employment_id) WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_contracts_employee_id_status ON lifecycle.contracts (employee_id, status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_contracts_metadata_gin ON lifecycle.contracts USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_contracts_metadata_deleted_at ON lifecycle.contracts ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_contracts_metadata_created_at ON lifecycle.contracts ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_contracts_metadata_updated_at ON lifecycle.contracts ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lifecycle.contracts_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS contracts_insert_audit ON lifecycle.contracts;
CREATE TRIGGER contracts_insert_audit BEFORE INSERT ON lifecycle.contracts
    FOR EACH ROW EXECUTE FUNCTION lifecycle.contracts_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS contracts_update_audit ON lifecycle.contracts;
CREATE TRIGGER contracts_update_audit BEFORE UPDATE ON lifecycle.contracts
    FOR EACH ROW EXECUTE FUNCTION lifecycle.contracts_audit_timestamp();
