-- Migration: Create promotions table
-- Generated by metaphor-schema

-- Create promotion_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_type') THEN
        CREATE TYPE promotion_type AS ENUM ('promotion', 'transfer', 'demotion', 'lateral');
    END IF;
END
$$;

-- Create promotion_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_status') THEN
        CREATE TYPE promotion_status AS ENUM ('draft', 'pending', 'approved', 'rejected', 'effective', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS lifecycle;

CREATE TABLE IF NOT EXISTS lifecycle.promotions (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    promotion_type promotion_type NOT NULL DEFAULT 'promotion',
    position_id_from UUID,
    position_id_to UUID,
    level_id_from UUID,
    level_id_to UUID,
    department_id_from UUID,
    department_id_to UUID,
    proposed_salary NUMERIC(18, 2) CHECK (proposed_salary >= 0),
    effective_date DATE NOT NULL,
    status promotion_status NOT NULL DEFAULT 'draft',
    requested_by UUID,
    approved_by UUID,
    appraisal_id UUID,
    reason TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_promotions_company_id_employee_id_effective_date ON lifecycle.promotions (company_id, employee_id, effective_date);

CREATE INDEX IF NOT EXISTS idx_promotions_status ON lifecycle.promotions (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_promotions_metadata_gin ON lifecycle.promotions USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_promotions_metadata_deleted_at ON lifecycle.promotions ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_promotions_metadata_created_at ON lifecycle.promotions ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_promotions_metadata_updated_at ON lifecycle.promotions ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lifecycle.promotions_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS promotions_insert_audit ON lifecycle.promotions;
CREATE TRIGGER promotions_insert_audit BEFORE INSERT ON lifecycle.promotions
    FOR EACH ROW EXECUTE FUNCTION lifecycle.promotions_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS promotions_update_audit ON lifecycle.promotions;
CREATE TRIGGER promotions_update_audit BEFORE UPDATE ON lifecycle.promotions
    FOR EACH ROW EXECUTE FUNCTION lifecycle.promotions_audit_timestamp();
