-- Enum types for lifecycle module
-- Generated by metaphor-schema

-- Create clearance_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'clearance_status') THEN
        CREATE TYPE clearance_status AS ENUM ('pending', 'cleared', 'blocked');
    END IF;
END
$$;

-- Create settlement_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'settlement_status') THEN
        CREATE TYPE settlement_status AS ENUM ('draft', 'confirmed', 'paid', 'disputed');
    END IF;
END
$$;

-- Create offboarding_reason enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offboarding_reason') THEN
        CREATE TYPE offboarding_reason AS ENUM ('resignation', 'termination', 'end_of_contract', 'retirement', 'death', 'merger_acquisition', 'efficiency', 'force_majeure', 'misconduct');
    END IF;
END
$$;

-- Create offboarding_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'offboarding_status') THEN
        CREATE TYPE offboarding_status AS ENUM ('initiated', 'in_progress', 'cleared', 'closed');
    END IF;
END
$$;

-- Create onboarding_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'onboarding_status') THEN
        CREATE TYPE onboarding_status AS ENUM ('pending', 'in_progress', 'completed', 'abandoned');
    END IF;
END
$$;

-- Create task_category enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_category') THEN
        CREATE TYPE task_category AS ENUM ('document', 'equipment', 'account_access', 'policy_ack', 'induction');
    END IF;
END
$$;

-- Create task_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'task_status') THEN
        CREATE TYPE task_status AS ENUM ('pending', 'done', 'skipped', 'blocked');
    END IF;
END
$$;

-- Create promotion_type enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_type') THEN
        CREATE TYPE promotion_type AS ENUM ('promotion', 'transfer', 'demotion', 'lateral');
    END IF;
END
$$;

-- Create promotion_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'promotion_status') THEN
        CREATE TYPE promotion_status AS ENUM ('draft', 'pending', 'approved', 'rejected', 'effective', 'cancelled');
    END IF;
END
$$;

