-- Migration: Create exit_interviews table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS lifecycle;

CREATE TABLE IF NOT EXISTS lifecycle.exit_interviews (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    employee_id UUID NOT NULL,
    offboarding_id UUID,
    conducted_by UUID,
    responses JSONB NOT NULL,
    would_recommend BOOLEAN,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_exit_interviews_company_id ON lifecycle.exit_interviews (company_id);

CREATE INDEX IF NOT EXISTS idx_exit_interviews_company_id_employee_id ON lifecycle.exit_interviews (company_id, employee_id);

CREATE INDEX IF NOT EXISTS idx_exit_interviews_offboarding_id ON lifecycle.exit_interviews (offboarding_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_exit_interviews_metadata_gin ON lifecycle.exit_interviews USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_exit_interviews_metadata_deleted_at ON lifecycle.exit_interviews ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_exit_interviews_metadata_created_at ON lifecycle.exit_interviews ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_exit_interviews_metadata_updated_at ON lifecycle.exit_interviews ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lifecycle.exit_interviews_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS exit_interviews_insert_audit ON lifecycle.exit_interviews;
CREATE TRIGGER exit_interviews_insert_audit BEFORE INSERT ON lifecycle.exit_interviews
    FOR EACH ROW EXECUTE FUNCTION lifecycle.exit_interviews_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS exit_interviews_update_audit ON lifecycle.exit_interviews;
CREATE TRIGGER exit_interviews_update_audit BEFORE UPDATE ON lifecycle.exit_interviews
    FOR EACH ROW EXECUTE FUNCTION lifecycle.exit_interviews_audit_timestamp();
