-- Migration: Create clearance_items table
-- Generated by metaphor-schema

-- Create clearance_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'clearance_status') THEN
        CREATE TYPE clearance_status AS ENUM ('pending', 'cleared', 'blocked');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS lifecycle;

CREATE TABLE IF NOT EXISTS lifecycle.clearance_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    company_id UUID NOT NULL,
    offboarding_id UUID NOT NULL,
    title TEXT NOT NULL,
    clearer_employee_id UUID,
    status clearance_status NOT NULL DEFAULT 'pending',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_clearance_items_company_id ON lifecycle.clearance_items (company_id);

CREATE INDEX IF NOT EXISTS idx_clearance_items_offboarding_id ON lifecycle.clearance_items (offboarding_id);

CREATE INDEX IF NOT EXISTS idx_clearance_items_status ON lifecycle.clearance_items (status);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_clearance_items_metadata_gin ON lifecycle.clearance_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_clearance_items_metadata_deleted_at ON lifecycle.clearance_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_clearance_items_metadata_created_at ON lifecycle.clearance_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_clearance_items_metadata_updated_at ON lifecycle.clearance_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION lifecycle.clearance_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS clearance_items_insert_audit ON lifecycle.clearance_items;
CREATE TRIGGER clearance_items_insert_audit BEFORE INSERT ON lifecycle.clearance_items
    FOR EACH ROW EXECUTE FUNCTION lifecycle.clearance_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS clearance_items_update_audit ON lifecycle.clearance_items;
CREATE TRIGGER clearance_items_update_audit BEFORE UPDATE ON lifecycle.clearance_items
    FOR EACH ROW EXECUTE FUNCTION lifecycle.clearance_items_audit_timestamp();
