//! Event handler trait for ClearanceItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ClearanceItemEvent;

/// Event handler for ClearanceItem events.
/// Implement this trait to react to ClearanceItem lifecycle events.
pub trait ClearanceItemEventHandler: EventHandler<ClearanceItemEvent> {}
