//! Domain events for ClearanceItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ClearanceItem;

/// Domain events for ClearanceItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ClearanceItem>)` variant.
pub type ClearanceItemEvent = CrudEvent<ClearanceItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ClearanceItem events.
pub type ClearanceItemEventPublisher = Arc<dyn CrudEventPublisher<ClearanceItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopClearanceItemEventPublisher = NoOpCrudEventPublisher<ClearanceItem>;
