//! Domain events for ContractTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ContractTemplate;

/// Domain events for ContractTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ContractTemplate>)` variant.
pub type ContractTemplateEvent = CrudEvent<ContractTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ContractTemplate events.
pub type ContractTemplateEventPublisher = Arc<dyn CrudEventPublisher<ContractTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopContractTemplateEventPublisher = NoOpCrudEventPublisher<ContractTemplate>;
