//! Domain events for Contract entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Contract;

/// Domain events for Contract — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Contract>)` variant.
pub type ContractEvent = CrudEvent<Contract>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Contract events.
pub type ContractEventPublisher = Arc<dyn CrudEventPublisher<Contract> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopContractEventPublisher = NoOpCrudEventPublisher<Contract>;
