//! Event handler trait for Contract events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ContractEvent;

/// Event handler for Contract events.
/// Implement this trait to react to Contract lifecycle events.
pub trait ContractEventHandler: EventHandler<ContractEvent> {}
