//! Domain events for DisciplineRecord entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DisciplineRecord;

/// Domain events for DisciplineRecord — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DisciplineRecord>)` variant.
pub type DisciplineRecordEvent = CrudEvent<DisciplineRecord>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DisciplineRecord events.
pub type DisciplineRecordEventPublisher = Arc<dyn CrudEventPublisher<DisciplineRecord> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDisciplineRecordEventPublisher = NoOpCrudEventPublisher<DisciplineRecord>;
