//! Event handler trait for DisciplineRecord events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DisciplineRecordEvent;

/// Event handler for DisciplineRecord events.
/// Implement this trait to react to DisciplineRecord lifecycle events.
pub trait DisciplineRecordEventHandler: EventHandler<DisciplineRecordEvent> {}
