//! Event handler trait for ExitInterview events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::ExitInterviewEvent;

/// Event handler for ExitInterview events.
/// Implement this trait to react to ExitInterview lifecycle events.
pub trait ExitInterviewEventHandler: EventHandler<ExitInterviewEvent> {}
