//! Domain events for ExitInterview entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ExitInterview;

/// Domain events for ExitInterview — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExitInterview>)` variant.
pub type ExitInterviewEvent = CrudEvent<ExitInterview>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExitInterview events.
pub type ExitInterviewEventPublisher = Arc<dyn CrudEventPublisher<ExitInterview> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExitInterviewEventPublisher = NoOpCrudEventPublisher<ExitInterview>;
