//! Event handler trait for FinalSettlement events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::FinalSettlementEvent;

/// Event handler for FinalSettlement events.
/// Implement this trait to react to FinalSettlement lifecycle events.
pub trait FinalSettlementEventHandler: EventHandler<FinalSettlementEvent> {}
