//! Domain events
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod clearance_item_events;
pub mod clearance_item_event_handlers;
pub mod contract_events;
pub mod contract_event_handlers;
pub mod contract_template_events;
pub mod contract_template_event_handlers;
pub mod discipline_record_events;
pub mod discipline_record_event_handlers;
pub mod exit_interview_events;
pub mod exit_interview_event_handlers;
pub mod final_settlement_events;
pub mod final_settlement_event_handlers;
pub mod offboarding_events;
pub mod offboarding_event_handlers;
pub mod onboarding_events;
pub mod onboarding_event_handlers;
pub mod onboarding_task_events;
pub mod onboarding_task_event_handlers;
pub mod onboarding_template_events;
pub mod onboarding_template_event_handlers;
pub mod onboarding_template_task_events;
pub mod onboarding_template_task_event_handlers;
pub mod promotion_events;
pub mod promotion_event_handlers;

pub use clearance_item_events::{ClearanceItemEvent, ClearanceItemEventPublisher, NoopClearanceItemEventPublisher};
pub use clearance_item_event_handlers::ClearanceItemEventHandler;
pub use contract_events::{ContractEvent, ContractEventPublisher, NoopContractEventPublisher};
pub use contract_event_handlers::ContractEventHandler;
pub use contract_template_events::{ContractTemplateEvent, ContractTemplateEventPublisher, NoopContractTemplateEventPublisher};
pub use contract_template_event_handlers::ContractTemplateEventHandler;
pub use discipline_record_events::{DisciplineRecordEvent, DisciplineRecordEventPublisher, NoopDisciplineRecordEventPublisher};
pub use discipline_record_event_handlers::DisciplineRecordEventHandler;
pub use exit_interview_events::{ExitInterviewEvent, ExitInterviewEventPublisher, NoopExitInterviewEventPublisher};
pub use exit_interview_event_handlers::ExitInterviewEventHandler;
pub use final_settlement_events::{FinalSettlementEvent, FinalSettlementEventPublisher, NoopFinalSettlementEventPublisher};
pub use final_settlement_event_handlers::FinalSettlementEventHandler;
pub use offboarding_events::{OffboardingEvent, OffboardingEventPublisher, NoopOffboardingEventPublisher};
pub use offboarding_event_handlers::OffboardingEventHandler;
pub use onboarding_events::{OnboardingEvent, OnboardingEventPublisher, NoopOnboardingEventPublisher};
pub use onboarding_event_handlers::OnboardingEventHandler;
pub use onboarding_task_events::{OnboardingTaskEvent, OnboardingTaskEventPublisher, NoopOnboardingTaskEventPublisher};
pub use onboarding_task_event_handlers::OnboardingTaskEventHandler;
pub use onboarding_template_events::{OnboardingTemplateEvent, OnboardingTemplateEventPublisher, NoopOnboardingTemplateEventPublisher};
pub use onboarding_template_event_handlers::OnboardingTemplateEventHandler;
pub use onboarding_template_task_events::{OnboardingTemplateTaskEvent, OnboardingTemplateTaskEventPublisher, NoopOnboardingTemplateTaskEventPublisher};
pub use onboarding_template_task_event_handlers::OnboardingTemplateTaskEventHandler;
pub use promotion_events::{PromotionEvent, PromotionEventPublisher, NoopPromotionEventPublisher};
pub use promotion_event_handlers::PromotionEventHandler;

// <<< CUSTOM
// END CUSTOM
