//! Event handler trait for Offboarding events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OffboardingEvent;

/// Event handler for Offboarding events.
/// Implement this trait to react to Offboarding lifecycle events.
pub trait OffboardingEventHandler: EventHandler<OffboardingEvent> {}
