//! Domain events for Onboarding entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Onboarding;

/// Domain events for Onboarding — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Onboarding>)` variant.
pub type OnboardingEvent = CrudEvent<Onboarding>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Onboarding events.
pub type OnboardingEventPublisher = Arc<dyn CrudEventPublisher<Onboarding> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOnboardingEventPublisher = NoOpCrudEventPublisher<Onboarding>;
