//! Event handler trait for Onboarding events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OnboardingEvent;

/// Event handler for Onboarding events.
/// Implement this trait to react to Onboarding lifecycle events.
pub trait OnboardingEventHandler: EventHandler<OnboardingEvent> {}
