//! Domain events for OnboardingTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::OnboardingTemplate;

/// Domain events for OnboardingTemplate — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<OnboardingTemplate>)` variant.
pub type OnboardingTemplateEvent = CrudEvent<OnboardingTemplate>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for OnboardingTemplate events.
pub type OnboardingTemplateEventPublisher = Arc<dyn CrudEventPublisher<OnboardingTemplate> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopOnboardingTemplateEventPublisher = NoOpCrudEventPublisher<OnboardingTemplate>;
