//! Event handler trait for OnboardingTemplateTask events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::OnboardingTemplateTaskEvent;

/// Event handler for OnboardingTemplateTask events.
/// Implement this trait to react to OnboardingTemplateTask lifecycle events.
pub trait OnboardingTemplateTaskEventHandler: EventHandler<OnboardingTemplateTaskEvent> {}
