//! Event handler trait for Promotion events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::PromotionEvent;

/// Event handler for Promotion events.
/// Implement this trait to react to Promotion lifecycle events.
pub trait PromotionEventHandler: EventHandler<PromotionEvent> {}
