//! ClearanceItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ClearanceItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CLEARANCEITEM SEEDER
// ============================================================================

/// Seeder for clearance_item
pub struct SeedClearanceItemSeeder;

impl SeedClearanceItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedClearanceItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedClearanceItemSeeder {
    fn name(&self) -> &'static str {
        "SeedClearanceItemSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if lifecycle.clearance_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM lifecycle.clearance_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/clearance_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM lifecycle.clearance_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

