//! ContractTemplate seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ContractTemplate data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// CONTRACTTEMPLATE SEEDER
// ============================================================================

/// Seeder for contract_template
pub struct SeedContractTemplateSeeder;

impl SeedContractTemplateSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedContractTemplateSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedContractTemplateSeeder {
    fn name(&self) -> &'static str {
        "SeedContractTemplateSeeder"
    }

    fn order(&self) -> i32 {
        3
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if lifecycle.contract_templates table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM lifecycle.contract_templates")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/contract_template_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM lifecycle.contract_templates")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

