//! DisciplineRecord seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial DisciplineRecord data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// DISCIPLINERECORD SEEDER
// ============================================================================

/// Seeder for discipline_record
pub struct SeedDisciplineRecordSeeder;

impl SeedDisciplineRecordSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedDisciplineRecordSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedDisciplineRecordSeeder {
    fn name(&self) -> &'static str {
        "SeedDisciplineRecordSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if lifecycle.discipline_records table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM lifecycle.discipline_records")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/discipline_record_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM lifecycle.discipline_records")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

