//! OnboardingTemplateTask seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial OnboardingTemplateTask data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// ONBOARDINGTEMPLATETASK SEEDER
// ============================================================================

/// Seeder for onboarding_template_task
pub struct SeedOnboardingTemplateTaskSeeder;

impl SeedOnboardingTemplateTaskSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedOnboardingTemplateTaskSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedOnboardingTemplateTaskSeeder {
    fn name(&self) -> &'static str {
        "SeedOnboardingTemplateTaskSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if lifecycle.onboarding_template_tasks table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM lifecycle.onboarding_template_tasks")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/onboarding_template_task_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM lifecycle.onboarding_template_tasks")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

