//! Repository trait for ContractTemplate aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ContractTemplate aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;

use crate::domain::entity::{ContractTemplate, ContractType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContractTemplatePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ContractTemplatePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ContractTemplatePaginatedResult {
    pub data: Vec<ContractTemplate>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContractTemplateFilter {
    pub name: Option<String>,
    pub contract_type: Option<ContractType>,
    pub body_template: Option<String>,
}

impl ContractTemplateFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.name.is_some() || self.contract_type.is_some() || self.body_template.is_some()
    }
}

/// Repository trait for ContractTemplate aggregate
///
/// This trait defines the persistence contract for ContractTemplate entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ContractTemplateRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new contract_template entity
    async fn save(&self, entity: &ContractTemplate) -> Result<ContractTemplate>;

    /// Find contract_template by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ContractTemplate>>;

    /// Find all contract_template entities
    async fn find_all(&self) -> Result<Vec<ContractTemplate>>;

    /// Update contract_template by ID
    async fn update(&self, id: &str, entity: &ContractTemplate) -> Result<Option<ContractTemplate>>;

    /// Delete contract_template by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List contract_template with pagination
    async fn list(&self, params: ContractTemplatePaginationParams) -> Result<ContractTemplatePaginatedResult>;

    /// List contract_template with pagination and filters
    async fn list_with_filters(&self, params: ContractTemplatePaginationParams, filters: ContractTemplateFilter) -> Result<ContractTemplatePaginatedResult>;

    /// Count all contract_template entities
    async fn count(&self) -> Result<u64>;

    /// Count contract_template entities matching filters
    async fn count_with_filters(&self, filters: ContractTemplateFilter) -> Result<u64>;

    /// Check if contract_template exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete contract_template by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted contract_template by ID
    async fn restore(&self, id: &str) -> Result<Option<ContractTemplate>>;

    /// List soft-deleted contract_template entities
    async fn list_deleted(&self, params: ContractTemplatePaginationParams) -> Result<ContractTemplatePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save contract_template entities
    async fn bulk_save(&self, entities: &[ContractTemplate]) -> Result<Vec<ContractTemplate>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
