//! Repository trait for Contract aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Contract aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Contract, ContractStatus, ContractType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContractPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ContractPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ContractPaginatedResult {
    pub data: Vec<Contract>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ContractFilter {
    pub employment_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub contract_type: Option<ContractType>,
    pub contract_no: Option<String>,
    pub status: Option<ContractStatus>,
    pub document_file_id: Option<Uuid>,
    pub template_id: Option<Uuid>,
    pub previous_contract_id: Option<Uuid>,
}

impl ContractFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employment_id.is_some() || self.employee_id.is_some() || self.contract_type.is_some() || self.contract_no.is_some() || self.status.is_some() || self.document_file_id.is_some() || self.template_id.is_some() || self.previous_contract_id.is_some()
    }
}

/// Repository trait for Contract aggregate
///
/// This trait defines the persistence contract for Contract entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ContractRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new contract entity
    async fn save(&self, entity: &Contract) -> Result<Contract>;

    /// Find contract by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Contract>>;

    /// Find all contract entities
    async fn find_all(&self) -> Result<Vec<Contract>>;

    /// Update contract by ID
    async fn update(&self, id: &str, entity: &Contract) -> Result<Option<Contract>>;

    /// Delete contract by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List contract with pagination
    async fn list(&self, params: ContractPaginationParams) -> Result<ContractPaginatedResult>;

    /// List contract with pagination and filters
    async fn list_with_filters(&self, params: ContractPaginationParams, filters: ContractFilter) -> Result<ContractPaginatedResult>;

    /// Count all contract entities
    async fn count(&self) -> Result<u64>;

    /// Count contract entities matching filters
    async fn count_with_filters(&self, filters: ContractFilter) -> Result<u64>;

    /// Check if contract exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete contract by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted contract by ID
    async fn restore(&self, id: &str) -> Result<Option<Contract>>;

    /// List soft-deleted contract entities
    async fn list_deleted(&self, params: ContractPaginationParams) -> Result<ContractPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save contract entities
    async fn bulk_save(&self, entities: &[Contract]) -> Result<Vec<Contract>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
