//! Repository trait for DisciplineRecord aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the DisciplineRecord aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{DisciplineRecord, DisciplineLevel, DisciplineServedDisposition, DisciplineStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DisciplineRecordPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl DisciplineRecordPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct DisciplineRecordPaginatedResult {
    pub data: Vec<DisciplineRecord>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct DisciplineRecordFilter {
    pub employee_id: Option<Uuid>,
    pub level: Option<DisciplineLevel>,
    pub offense: Option<String>,
    pub description: Option<String>,
    pub served_disposition: Option<DisciplineServedDisposition>,
    pub status: Option<DisciplineStatus>,
    pub acknowledged_via: Option<String>,
    pub document_file_id: Option<Uuid>,
    pub cancel_reason: Option<String>,
    pub issued_by: Option<Uuid>,
}

impl DisciplineRecordFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.employee_id.is_some() || self.level.is_some() || self.offense.is_some() || self.description.is_some() || self.served_disposition.is_some() || self.status.is_some() || self.acknowledged_via.is_some() || self.document_file_id.is_some() || self.cancel_reason.is_some() || self.issued_by.is_some()
    }
}

/// Repository trait for DisciplineRecord aggregate
///
/// This trait defines the persistence contract for DisciplineRecord entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait DisciplineRecordRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new discipline_record entity
    async fn save(&self, entity: &DisciplineRecord) -> Result<DisciplineRecord>;

    /// Find discipline_record by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<DisciplineRecord>>;

    /// Find all discipline_record entities
    async fn find_all(&self) -> Result<Vec<DisciplineRecord>>;

    /// Update discipline_record by ID
    async fn update(&self, id: &str, entity: &DisciplineRecord) -> Result<Option<DisciplineRecord>>;

    /// Delete discipline_record by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List discipline_record with pagination
    async fn list(&self, params: DisciplineRecordPaginationParams) -> Result<DisciplineRecordPaginatedResult>;

    /// List discipline_record with pagination and filters
    async fn list_with_filters(&self, params: DisciplineRecordPaginationParams, filters: DisciplineRecordFilter) -> Result<DisciplineRecordPaginatedResult>;

    /// Count all discipline_record entities
    async fn count(&self) -> Result<u64>;

    /// Count discipline_record entities matching filters
    async fn count_with_filters(&self, filters: DisciplineRecordFilter) -> Result<u64>;

    /// Check if discipline_record exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete discipline_record by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted discipline_record by ID
    async fn restore(&self, id: &str) -> Result<Option<DisciplineRecord>>;

    /// List soft-deleted discipline_record entities
    async fn list_deleted(&self, params: DisciplineRecordPaginationParams) -> Result<DisciplineRecordPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save discipline_record entities
    async fn bulk_save(&self, entities: &[DisciplineRecord]) -> Result<Vec<DisciplineRecord>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
