//! Repository trait for ExitInterview aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the ExitInterview aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::ExitInterview;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExitInterviewPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl ExitInterviewPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct ExitInterviewPaginatedResult {
    pub data: Vec<ExitInterview>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct ExitInterviewFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub offboarding_id: Option<Uuid>,
    pub conducted_by: Option<Uuid>,
    pub would_recommend: Option<bool>,
}

impl ExitInterviewFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.offboarding_id.is_some() || self.conducted_by.is_some() || self.would_recommend.is_some()
    }
}

/// Repository trait for ExitInterview aggregate
///
/// This trait defines the persistence contract for ExitInterview entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait ExitInterviewRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new exit_interview entity
    async fn save(&self, entity: &ExitInterview) -> Result<ExitInterview>;

    /// Find exit_interview by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<ExitInterview>>;

    /// Find all exit_interview entities
    async fn find_all(&self) -> Result<Vec<ExitInterview>>;

    /// Update exit_interview by ID
    async fn update(&self, id: &str, entity: &ExitInterview) -> Result<Option<ExitInterview>>;

    /// Delete exit_interview by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List exit_interview with pagination
    async fn list(&self, params: ExitInterviewPaginationParams) -> Result<ExitInterviewPaginatedResult>;

    /// List exit_interview with pagination and filters
    async fn list_with_filters(&self, params: ExitInterviewPaginationParams, filters: ExitInterviewFilter) -> Result<ExitInterviewPaginatedResult>;

    /// Count all exit_interview entities
    async fn count(&self) -> Result<u64>;

    /// Count exit_interview entities matching filters
    async fn count_with_filters(&self, filters: ExitInterviewFilter) -> Result<u64>;

    /// Check if exit_interview exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete exit_interview by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted exit_interview by ID
    async fn restore(&self, id: &str) -> Result<Option<ExitInterview>>;

    /// List soft-deleted exit_interview entities
    async fn list_deleted(&self, params: ExitInterviewPaginationParams) -> Result<ExitInterviewPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save exit_interview entities
    async fn bulk_save(&self, entities: &[ExitInterview]) -> Result<Vec<ExitInterview>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
