//! Repository trait for FinalSettlement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the FinalSettlement aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{FinalSettlement, SettlementStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FinalSettlementPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl FinalSettlementPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct FinalSettlementPaginatedResult {
    pub data: Vec<FinalSettlement>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct FinalSettlementFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub offboarding_id: Option<Uuid>,
    pub period: Option<String>,
    pub status: Option<SettlementStatus>,
    pub accounting_post_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
}

impl FinalSettlementFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.offboarding_id.is_some() || self.period.is_some() || self.status.is_some() || self.accounting_post_id.is_some() || self.journal_id.is_some()
    }
}

/// Repository trait for FinalSettlement aggregate
///
/// This trait defines the persistence contract for FinalSettlement entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait FinalSettlementRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new final_settlement entity
    async fn save(&self, entity: &FinalSettlement) -> Result<FinalSettlement>;

    /// Find final_settlement by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<FinalSettlement>>;

    /// Find all final_settlement entities
    async fn find_all(&self) -> Result<Vec<FinalSettlement>>;

    /// Update final_settlement by ID
    async fn update(&self, id: &str, entity: &FinalSettlement) -> Result<Option<FinalSettlement>>;

    /// Delete final_settlement by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List final_settlement with pagination
    async fn list(&self, params: FinalSettlementPaginationParams) -> Result<FinalSettlementPaginatedResult>;

    /// List final_settlement with pagination and filters
    async fn list_with_filters(&self, params: FinalSettlementPaginationParams, filters: FinalSettlementFilter) -> Result<FinalSettlementPaginatedResult>;

    /// Count all final_settlement entities
    async fn count(&self) -> Result<u64>;

    /// Count final_settlement entities matching filters
    async fn count_with_filters(&self, filters: FinalSettlementFilter) -> Result<u64>;

    /// Check if final_settlement exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete final_settlement by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted final_settlement by ID
    async fn restore(&self, id: &str) -> Result<Option<FinalSettlement>>;

    /// List soft-deleted final_settlement entities
    async fn list_deleted(&self, params: FinalSettlementPaginationParams) -> Result<FinalSettlementPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save final_settlement entities
    async fn bulk_save(&self, entities: &[FinalSettlement]) -> Result<Vec<FinalSettlement>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
