//! Repository trait for Offboarding aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Offboarding aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Offboarding, OffboardingReason, OffboardingStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OffboardingPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OffboardingPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OffboardingPaginatedResult {
    pub data: Vec<Offboarding>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OffboardingFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub reason: Option<OffboardingReason>,
    pub status: Option<OffboardingStatus>,
}

impl OffboardingFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.reason.is_some() || self.status.is_some()
    }
}

/// Repository trait for Offboarding aggregate
///
/// This trait defines the persistence contract for Offboarding entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OffboardingRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new offboarding entity
    async fn save(&self, entity: &Offboarding) -> Result<Offboarding>;

    /// Find offboarding by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Offboarding>>;

    /// Find all offboarding entities
    async fn find_all(&self) -> Result<Vec<Offboarding>>;

    /// Update offboarding by ID
    async fn update(&self, id: &str, entity: &Offboarding) -> Result<Option<Offboarding>>;

    /// Delete offboarding by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List offboarding with pagination
    async fn list(&self, params: OffboardingPaginationParams) -> Result<OffboardingPaginatedResult>;

    /// List offboarding with pagination and filters
    async fn list_with_filters(&self, params: OffboardingPaginationParams, filters: OffboardingFilter) -> Result<OffboardingPaginatedResult>;

    /// Count all offboarding entities
    async fn count(&self) -> Result<u64>;

    /// Count offboarding entities matching filters
    async fn count_with_filters(&self, filters: OffboardingFilter) -> Result<u64>;

    /// Check if offboarding exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete offboarding by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted offboarding by ID
    async fn restore(&self, id: &str) -> Result<Option<Offboarding>>;

    /// List soft-deleted offboarding entities
    async fn list_deleted(&self, params: OffboardingPaginationParams) -> Result<OffboardingPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save offboarding entities
    async fn bulk_save(&self, entities: &[Offboarding]) -> Result<Vec<Offboarding>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
