//! Repository trait for OnboardingTask aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OnboardingTask aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{OnboardingTask, TaskCategory, TaskStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OnboardingTaskPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OnboardingTaskPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OnboardingTaskPaginatedResult {
    pub data: Vec<OnboardingTask>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OnboardingTaskFilter {
    pub company_id: Option<Uuid>,
    pub onboarding_id: Option<Uuid>,
    pub title: Option<String>,
    pub category: Option<TaskCategory>,
    pub owner_employee_id: Option<Uuid>,
    pub status: Option<TaskStatus>,
}

impl OnboardingTaskFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.onboarding_id.is_some() || self.title.is_some() || self.category.is_some() || self.owner_employee_id.is_some() || self.status.is_some()
    }
}

/// Repository trait for OnboardingTask aggregate
///
/// This trait defines the persistence contract for OnboardingTask entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OnboardingTaskRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new onboarding_task entity
    async fn save(&self, entity: &OnboardingTask) -> Result<OnboardingTask>;

    /// Find onboarding_task by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OnboardingTask>>;

    /// Find all onboarding_task entities
    async fn find_all(&self) -> Result<Vec<OnboardingTask>>;

    /// Update onboarding_task by ID
    async fn update(&self, id: &str, entity: &OnboardingTask) -> Result<Option<OnboardingTask>>;

    /// Delete onboarding_task by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List onboarding_task with pagination
    async fn list(&self, params: OnboardingTaskPaginationParams) -> Result<OnboardingTaskPaginatedResult>;

    /// List onboarding_task with pagination and filters
    async fn list_with_filters(&self, params: OnboardingTaskPaginationParams, filters: OnboardingTaskFilter) -> Result<OnboardingTaskPaginatedResult>;

    /// Count all onboarding_task entities
    async fn count(&self) -> Result<u64>;

    /// Count onboarding_task entities matching filters
    async fn count_with_filters(&self, filters: OnboardingTaskFilter) -> Result<u64>;

    /// Check if onboarding_task exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete onboarding_task by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted onboarding_task by ID
    async fn restore(&self, id: &str) -> Result<Option<OnboardingTask>>;

    /// List soft-deleted onboarding_task entities
    async fn list_deleted(&self, params: OnboardingTaskPaginationParams) -> Result<OnboardingTaskPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save onboarding_task entities
    async fn bulk_save(&self, entities: &[OnboardingTask]) -> Result<Vec<OnboardingTask>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
