//! Repository trait for OnboardingTemplateTask aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the OnboardingTemplateTask aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::OnboardingTemplateTask;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OnboardingTemplateTaskPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl OnboardingTemplateTaskPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct OnboardingTemplateTaskPaginatedResult {
    pub data: Vec<OnboardingTemplateTask>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct OnboardingTemplateTaskFilter {
    pub template_id: Option<Uuid>,
    pub title: Option<String>,
    pub category: Option<String>,
    pub owner_role: Option<String>,
}

impl OnboardingTemplateTaskFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.template_id.is_some() || self.title.is_some() || self.category.is_some() || self.owner_role.is_some()
    }
}

/// Repository trait for OnboardingTemplateTask aggregate
///
/// This trait defines the persistence contract for OnboardingTemplateTask entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait OnboardingTemplateTaskRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new onboarding_template_task entity
    async fn save(&self, entity: &OnboardingTemplateTask) -> Result<OnboardingTemplateTask>;

    /// Find onboarding_template_task by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<OnboardingTemplateTask>>;

    /// Find all onboarding_template_task entities
    async fn find_all(&self) -> Result<Vec<OnboardingTemplateTask>>;

    /// Update onboarding_template_task by ID
    async fn update(&self, id: &str, entity: &OnboardingTemplateTask) -> Result<Option<OnboardingTemplateTask>>;

    /// Delete onboarding_template_task by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List onboarding_template_task with pagination
    async fn list(&self, params: OnboardingTemplateTaskPaginationParams) -> Result<OnboardingTemplateTaskPaginatedResult>;

    /// List onboarding_template_task with pagination and filters
    async fn list_with_filters(&self, params: OnboardingTemplateTaskPaginationParams, filters: OnboardingTemplateTaskFilter) -> Result<OnboardingTemplateTaskPaginatedResult>;

    /// Count all onboarding_template_task entities
    async fn count(&self) -> Result<u64>;

    /// Count onboarding_template_task entities matching filters
    async fn count_with_filters(&self, filters: OnboardingTemplateTaskFilter) -> Result<u64>;

    /// Check if onboarding_template_task exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete onboarding_template_task by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted onboarding_template_task by ID
    async fn restore(&self, id: &str) -> Result<Option<OnboardingTemplateTask>>;

    /// List soft-deleted onboarding_template_task entities
    async fn list_deleted(&self, params: OnboardingTemplateTaskPaginationParams) -> Result<OnboardingTemplateTaskPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save onboarding_template_task entities
    async fn bulk_save(&self, entities: &[OnboardingTemplateTask]) -> Result<Vec<OnboardingTemplateTask>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
