//! Repository trait for Promotion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Promotion aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Promotion, PromotionStatus, PromotionType};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromotionPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl PromotionPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct PromotionPaginatedResult {
    pub data: Vec<Promotion>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct PromotionFilter {
    pub company_id: Option<Uuid>,
    pub employee_id: Option<Uuid>,
    pub promotion_type: Option<PromotionType>,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub status: Option<PromotionStatus>,
    pub requested_by: Option<Uuid>,
    pub approved_by: Option<Uuid>,
    pub appraisal_id: Option<Uuid>,
    pub reason: Option<String>,
}

impl PromotionFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.employee_id.is_some() || self.promotion_type.is_some() || self.position_id_from.is_some() || self.position_id_to.is_some() || self.level_id_from.is_some() || self.level_id_to.is_some() || self.department_id_from.is_some() || self.department_id_to.is_some() || self.status.is_some() || self.requested_by.is_some() || self.approved_by.is_some() || self.appraisal_id.is_some() || self.reason.is_some()
    }
}

/// Repository trait for Promotion aggregate
///
/// This trait defines the persistence contract for Promotion entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait PromotionRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new promotion entity
    async fn save(&self, entity: &Promotion) -> Result<Promotion>;

    /// Find promotion by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Promotion>>;

    /// Find all promotion entities
    async fn find_all(&self) -> Result<Vec<Promotion>>;

    /// Update promotion by ID
    async fn update(&self, id: &str, entity: &Promotion) -> Result<Option<Promotion>>;

    /// Delete promotion by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List promotion with pagination
    async fn list(&self, params: PromotionPaginationParams) -> Result<PromotionPaginatedResult>;

    /// List promotion with pagination and filters
    async fn list_with_filters(&self, params: PromotionPaginationParams, filters: PromotionFilter) -> Result<PromotionPaginatedResult>;

    /// Count all promotion entities
    async fn count(&self) -> Result<u64>;

    /// Count promotion entities matching filters
    async fn count_with_filters(&self, filters: PromotionFilter) -> Result<u64>;

    /// Check if promotion exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete promotion by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted promotion by ID
    async fn restore(&self, id: &str) -> Result<Option<Promotion>>;

    /// List soft-deleted promotion entities
    async fn list_deleted(&self, params: PromotionPaginationParams) -> Result<PromotionPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save promotion entities
    async fn bulk_save(&self, entities: &[Promotion]) -> Result<Vec<Promotion>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
