//! Repository for ClearanceItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ClearanceItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ClearanceItem;

/// Table name for ClearanceItem entities
pub const TABLE_NAME: &str = "lifecycle.clearance_items";

/// Repository for ClearanceItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ClearanceItemRepository(
    backbone_orm::GenericCrudRepository<ClearanceItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ClearanceItemRepository {
    type Target = backbone_orm::GenericCrudRepository<ClearanceItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ClearanceItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ClearanceItemRepository, ClearanceItem, soft_delete);
