//! Repository for ContractTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ContractTemplate, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ContractTemplate;

/// Table name for ContractTemplate entities
pub const TABLE_NAME: &str = "lifecycle.contract_templates";

/// Repository for ContractTemplate entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ContractTemplateRepository(
    backbone_orm::GenericCrudRepository<ContractTemplate, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ContractTemplateRepository {
    type Target = backbone_orm::GenericCrudRepository<ContractTemplate, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ContractTemplateRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ContractTemplateRepository, ContractTemplate, soft_delete);
