//! Repository for ExitInterview entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<ExitInterview, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::ExitInterview;

/// Table name for ExitInterview entities
pub const TABLE_NAME: &str = "lifecycle.exit_interviews";

/// Repository for ExitInterview entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct ExitInterviewRepository(
    backbone_orm::GenericCrudRepository<ExitInterview, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for ExitInterviewRepository {
    type Target = backbone_orm::GenericCrudRepository<ExitInterview, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl ExitInterviewRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(ExitInterviewRepository, ExitInterview, soft_delete);
