//! Repository for FinalSettlement entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<FinalSettlement, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::FinalSettlement;

/// Table name for FinalSettlement entities
pub const TABLE_NAME: &str = "lifecycle.final_settlements";

/// Repository for FinalSettlement entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct FinalSettlementRepository(
    backbone_orm::GenericCrudRepository<FinalSettlement, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for FinalSettlementRepository {
    type Target = backbone_orm::GenericCrudRepository<FinalSettlement, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl FinalSettlementRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(FinalSettlementRepository, FinalSettlement, soft_delete);
