//! Repository for Offboarding entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Offboarding, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Offboarding;

/// Table name for Offboarding entities
pub const TABLE_NAME: &str = "lifecycle.offboardings";

/// Repository for Offboarding entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OffboardingRepository(
    backbone_orm::GenericCrudRepository<Offboarding, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OffboardingRepository {
    type Target = backbone_orm::GenericCrudRepository<Offboarding, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OffboardingRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OffboardingRepository, Offboarding, soft_delete);
