//! Repository for OnboardingTemplateTask entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OnboardingTemplateTask, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OnboardingTemplateTask;

/// Table name for OnboardingTemplateTask entities
pub const TABLE_NAME: &str = "lifecycle.onboarding_template_tasks";

/// Repository for OnboardingTemplateTask entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OnboardingTemplateTaskRepository(
    backbone_orm::GenericCrudRepository<OnboardingTemplateTask, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OnboardingTemplateTaskRepository {
    type Target = backbone_orm::GenericCrudRepository<OnboardingTemplateTask, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OnboardingTemplateTaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OnboardingTemplateTaskRepository, OnboardingTemplateTask, soft_delete);
