//! Repository for OnboardingTask entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<OnboardingTask, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::OnboardingTask;

/// Table name for OnboardingTask entities
pub const TABLE_NAME: &str = "lifecycle.onboarding_tasks";

/// Repository for OnboardingTask entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct OnboardingTaskRepository(
    backbone_orm::GenericCrudRepository<OnboardingTask, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for OnboardingTaskRepository {
    type Target = backbone_orm::GenericCrudRepository<OnboardingTask, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl OnboardingTaskRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(OnboardingTaskRepository, OnboardingTask, soft_delete);
