//! Repository for Promotion entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Promotion, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::Promotion;

/// Table name for Promotion entities
pub const TABLE_NAME: &str = "lifecycle.promotions";

/// Repository for Promotion entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct PromotionRepository(
    backbone_orm::GenericCrudRepository<Promotion, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for PromotionRepository {
    type Target = backbone_orm::GenericCrudRepository<Promotion, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl PromotionRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(PromotionRepository, Promotion, soft_delete);
