//! Validator for ClearanceItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ClearanceItem>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ClearanceItem;

/// Validator type alias for ClearanceItem entities.
pub type ClearanceItemValidator = EntityValidator<ClearanceItem>;

/// Build a validator for ClearanceItem with all schema-defined field rules.
pub fn clearance_item_validator() -> ClearanceItemValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &ClearanceItem| &e.title))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
