//! Validator for Contract entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Contract>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank};
use crate::domain::entity::Contract;

/// Validator type alias for Contract entities.
pub type ContractValidator = EntityValidator<Contract>;

/// Build a validator for Contract with all schema-defined field rules.
pub fn contract_validator() -> ContractValidator {
    EntityValidator::new()
        .rule(OptionalNotBlank::new("contract_no", |e: &Contract| e.contract_no.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
