//! Validator for ContractTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<ContractTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{RequiredString};
use crate::domain::entity::ContractTemplate;

/// Validator type alias for ContractTemplate entities.
pub type ContractTemplateValidator = EntityValidator<ContractTemplate>;

/// Build a validator for ContractTemplate with all schema-defined field rules.
pub fn contract_template_validator() -> ContractTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &ContractTemplate| &e.name))
        .rule(RequiredString::new("body_template", |e: &ContractTemplate| &e.body_template))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
