//! Validator for DisciplineRecord entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DisciplineRecord>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::DisciplineRecord;

/// Validator type alias for DisciplineRecord entities.
pub type DisciplineRecordValidator = EntityValidator<DisciplineRecord>;

/// Build a validator for DisciplineRecord with all schema-defined field rules.
pub fn discipline_record_validator() -> DisciplineRecordValidator {
    EntityValidator::new()
        .rule(RequiredString::new("offense", |e: &DisciplineRecord| &e.offense))
        .rule(RequiredString::new("description", |e: &DisciplineRecord| &e.description))
        .rule(OptionalNotBlank::new("acknowledged_via", |e: &DisciplineRecord| e.acknowledged_via.as_deref()))
        .rule(OptionalNotBlank::new("cancel_reason", |e: &DisciplineRecord| e.cancel_reason.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
