//! Validator for FinalSettlement entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<FinalSettlement>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, RequiredString};
use crate::domain::entity::FinalSettlement;

/// Validator type alias for FinalSettlement entities.
pub type FinalSettlementValidator = EntityValidator<FinalSettlement>;

/// Build a validator for FinalSettlement with all schema-defined field rules.
pub fn final_settlement_validator() -> FinalSettlementValidator {
    EntityValidator::new()
        .rule(RequiredString::new("period", |e: &FinalSettlement| &e.period))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
