//! Validator for Offboarding entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Offboarding>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::Offboarding;

/// Validator type alias for Offboarding entities.
pub type OffboardingValidator = EntityValidator<Offboarding>;

/// Build a validator for Offboarding with all schema-defined field rules.
pub fn offboarding_validator() -> OffboardingValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
