//! Validator for OnboardingTemplate entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OnboardingTemplate>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::OnboardingTemplate;

/// Validator type alias for OnboardingTemplate entities.
pub type OnboardingTemplateValidator = EntityValidator<OnboardingTemplate>;

/// Build a validator for OnboardingTemplate with all schema-defined field rules.
pub fn onboarding_template_validator() -> OnboardingTemplateValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &OnboardingTemplate| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &OnboardingTemplate| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
