//! Validator for OnboardingTemplateTask entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<OnboardingTemplateTask>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::OnboardingTemplateTask;

/// Validator type alias for OnboardingTemplateTask entities.
pub type OnboardingTemplateTaskValidator = EntityValidator<OnboardingTemplateTask>;

/// Build a validator for OnboardingTemplateTask with all schema-defined field rules.
pub fn onboarding_template_task_validator() -> OnboardingTemplateTaskValidator {
    EntityValidator::new()
        .rule(RequiredString::new("title", |e: &OnboardingTemplateTask| &e.title))
        .rule(OptionalNotBlank::new("category", |e: &OnboardingTemplateTask| e.category.as_deref()))
        .rule(OptionalNotBlank::new("owner_role", |e: &OnboardingTemplateTask| e.owner_role.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
