//! Validator for Onboarding entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<Onboarding>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use crate::domain::entity::Onboarding;

/// Validator type alias for Onboarding entities.
pub type OnboardingValidator = EntityValidator<Onboarding>;

/// Build a validator for Onboarding with all schema-defined field rules.
pub fn onboarding_validator() -> OnboardingValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
