//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod clearance_item;
pub mod exit_interview;
pub mod final_settlement;
pub mod offboarding;
pub mod onboarding;
pub mod onboarding_task;
pub mod promotion;
pub mod clearance_status;
pub mod settlement_status;
pub mod offboarding_reason;
pub mod offboarding_status;
pub mod onboarding_status;
pub mod task_category;
pub mod task_status;
pub mod promotion_type;
pub mod promotion_status;

// Re-exports
pub use clearance_item::ClearanceItem;
pub use clearance_item::ClearanceItemBuilder;
pub use clearance_item::ClearanceItemId;
pub use exit_interview::ExitInterview;
pub use exit_interview::ExitInterviewBuilder;
pub use exit_interview::ExitInterviewId;
pub use final_settlement::FinalSettlement;
pub use final_settlement::FinalSettlementBuilder;
pub use final_settlement::FinalSettlementId;
pub use offboarding::Offboarding;
pub use offboarding::OffboardingBuilder;
pub use offboarding::OffboardingId;
pub use onboarding::Onboarding;
pub use onboarding::OnboardingBuilder;
pub use onboarding::OnboardingId;
pub use onboarding_task::OnboardingTask;
pub use onboarding_task::OnboardingTaskBuilder;
pub use onboarding_task::OnboardingTaskId;
pub use promotion::Promotion;
pub use promotion::PromotionBuilder;
pub use promotion::PromotionId;
pub use clearance_status::ClearanceStatus;
pub use settlement_status::SettlementStatus;
pub use offboarding_reason::OffboardingReason;
pub use offboarding_status::OffboardingStatus;
pub use onboarding_status::OnboardingStatus;
pub use task_category::TaskCategory;
pub use task_status::TaskStatus;
pub use promotion_type::PromotionType;
pub use promotion_status::PromotionStatus;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
