//! Auth configuration for ClearanceItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<ClearanceItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::ClearanceItemService;
use crate::domain::entity::ClearanceItem;

/// Permission string constants for ClearanceItem operations.
pub mod permissions {
    pub const LIST:        &str = "clearance_item:list";
    pub const READ:        &str = "clearance_item:read";
    pub const CREATE:      &str = "clearance_item:create";
    pub const UPDATE:      &str = "clearance_item:update";
    pub const DELETE:      &str = "clearance_item:delete";
    pub const RESTORE:     &str = "clearance_item:restore";
    pub const TRASH:       &str = "clearance_item:trash";
    pub const EMPTY_TRASH: &str = "clearance_item:empty_trash";
    pub const BULK_CREATE: &str = "clearance_item:bulk_create";
    pub const UPSERT:      &str = "clearance_item:upsert";
}

/// Resource policy for ClearanceItem — maps CRUD actions to permission strings.
pub struct ClearanceItemPolicy;

#[async_trait]
impl ResourcePolicy<ClearanceItem> for ClearanceItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &ClearanceItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for ClearanceItem handlers.
///
/// Wraps `ClearanceItemService` and checks `ClearanceItemPolicy` before delegating.
pub type ClearanceItemGuard = PermissionGuard<ClearanceItem>;

/// Service-integrated permission guard for ClearanceItem (for use in generated handlers).
pub type ClearanceItemServiceGuard = ServicePermissionGuard<ClearanceItem, ClearanceItemService, ClearanceItemPolicy>;

// <<< CUSTOM
// END CUSTOM
