//! Auth configuration for FinalSettlement handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<FinalSettlement>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::FinalSettlementService;
use crate::domain::entity::FinalSettlement;

/// Permission string constants for FinalSettlement operations.
pub mod permissions {
    pub const LIST:        &str = "final_settlement:list";
    pub const READ:        &str = "final_settlement:read";
    pub const CREATE:      &str = "final_settlement:create";
    pub const UPDATE:      &str = "final_settlement:update";
    pub const DELETE:      &str = "final_settlement:delete";
    pub const RESTORE:     &str = "final_settlement:restore";
    pub const TRASH:       &str = "final_settlement:trash";
    pub const EMPTY_TRASH: &str = "final_settlement:empty_trash";
    pub const BULK_CREATE: &str = "final_settlement:bulk_create";
    pub const UPSERT:      &str = "final_settlement:upsert";
}

/// Resource policy for FinalSettlement — maps CRUD actions to permission strings.
pub struct FinalSettlementPolicy;

#[async_trait]
impl ResourcePolicy<FinalSettlement> for FinalSettlementPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &FinalSettlement,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for FinalSettlement handlers.
///
/// Wraps `FinalSettlementService` and checks `FinalSettlementPolicy` before delegating.
pub type FinalSettlementGuard = PermissionGuard<FinalSettlement>;

/// Service-integrated permission guard for FinalSettlement (for use in generated handlers).
pub type FinalSettlementServiceGuard = ServicePermissionGuard<FinalSettlement, FinalSettlementService, FinalSettlementPolicy>;

// <<< CUSTOM
// END CUSTOM
