//! Auth policies and guards
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod clearance_item_auth;
pub mod exit_interview_auth;
pub mod final_settlement_auth;
pub mod offboarding_auth;
pub mod onboarding_auth;
pub mod onboarding_task_auth;
pub mod promotion_auth;

pub use clearance_item_auth::{ClearanceItemPolicy, ClearanceItemGuard, ClearanceItemServiceGuard};
pub use exit_interview_auth::{ExitInterviewPolicy, ExitInterviewGuard, ExitInterviewServiceGuard};
pub use final_settlement_auth::{FinalSettlementPolicy, FinalSettlementGuard, FinalSettlementServiceGuard};
pub use offboarding_auth::{OffboardingPolicy, OffboardingGuard, OffboardingServiceGuard};
pub use onboarding_auth::{OnboardingPolicy, OnboardingGuard, OnboardingServiceGuard};
pub use onboarding_task_auth::{OnboardingTaskPolicy, OnboardingTaskGuard, OnboardingTaskServiceGuard};
pub use promotion_auth::{PromotionPolicy, PromotionGuard, PromotionServiceGuard};

// <<< CUSTOM
// END CUSTOM
