//! Auth configuration for Offboarding handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Offboarding>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OffboardingService;
use crate::domain::entity::Offboarding;

/// Permission string constants for Offboarding operations.
pub mod permissions {
    pub const LIST:        &str = "offboarding:list";
    pub const READ:        &str = "offboarding:read";
    pub const CREATE:      &str = "offboarding:create";
    pub const UPDATE:      &str = "offboarding:update";
    pub const DELETE:      &str = "offboarding:delete";
    pub const RESTORE:     &str = "offboarding:restore";
    pub const TRASH:       &str = "offboarding:trash";
    pub const EMPTY_TRASH: &str = "offboarding:empty_trash";
    pub const BULK_CREATE: &str = "offboarding:bulk_create";
    pub const UPSERT:      &str = "offboarding:upsert";
}

/// Resource policy for Offboarding — maps CRUD actions to permission strings.
pub struct OffboardingPolicy;

#[async_trait]
impl ResourcePolicy<Offboarding> for OffboardingPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Offboarding,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Offboarding handlers.
///
/// Wraps `OffboardingService` and checks `OffboardingPolicy` before delegating.
pub type OffboardingGuard = PermissionGuard<Offboarding>;

/// Service-integrated permission guard for Offboarding (for use in generated handlers).
pub type OffboardingServiceGuard = ServicePermissionGuard<Offboarding, OffboardingService, OffboardingPolicy>;

// <<< CUSTOM
// END CUSTOM
