//! Auth configuration for Onboarding handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Onboarding>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::OnboardingService;
use crate::domain::entity::Onboarding;

/// Permission string constants for Onboarding operations.
pub mod permissions {
    pub const LIST:        &str = "onboarding:list";
    pub const READ:        &str = "onboarding:read";
    pub const CREATE:      &str = "onboarding:create";
    pub const UPDATE:      &str = "onboarding:update";
    pub const DELETE:      &str = "onboarding:delete";
    pub const RESTORE:     &str = "onboarding:restore";
    pub const TRASH:       &str = "onboarding:trash";
    pub const EMPTY_TRASH: &str = "onboarding:empty_trash";
    pub const BULK_CREATE: &str = "onboarding:bulk_create";
    pub const UPSERT:      &str = "onboarding:upsert";
}

/// Resource policy for Onboarding — maps CRUD actions to permission strings.
pub struct OnboardingPolicy;

#[async_trait]
impl ResourcePolicy<Onboarding> for OnboardingPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Onboarding,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Onboarding handlers.
///
/// Wraps `OnboardingService` and checks `OnboardingPolicy` before delegating.
pub type OnboardingGuard = PermissionGuard<Onboarding>;

/// Service-integrated permission guard for Onboarding (for use in generated handlers).
pub type OnboardingServiceGuard = ServicePermissionGuard<Onboarding, OnboardingService, OnboardingPolicy>;

// <<< CUSTOM
// END CUSTOM
