//! Auth configuration for Promotion handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Promotion>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::PromotionService;
use crate::domain::entity::Promotion;

/// Permission string constants for Promotion operations.
pub mod permissions {
    pub const LIST:        &str = "promotion:list";
    pub const READ:        &str = "promotion:read";
    pub const CREATE:      &str = "promotion:create";
    pub const UPDATE:      &str = "promotion:update";
    pub const DELETE:      &str = "promotion:delete";
    pub const RESTORE:     &str = "promotion:restore";
    pub const TRASH:       &str = "promotion:trash";
    pub const EMPTY_TRASH: &str = "promotion:empty_trash";
    pub const BULK_CREATE: &str = "promotion:bulk_create";
    pub const UPSERT:      &str = "promotion:upsert";
}

/// Resource policy for Promotion — maps CRUD actions to permission strings.
pub struct PromotionPolicy;

#[async_trait]
impl ResourcePolicy<Promotion> for PromotionPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Promotion,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Promotion handlers.
///
/// Wraps `PromotionService` and checks `PromotionPolicy` before delegating.
pub type PromotionGuard = PermissionGuard<Promotion>;

/// Service-integrated permission guard for Promotion (for use in generated handlers).
pub type PromotionServiceGuard = ServicePermissionGuard<Promotion, PromotionService, PromotionPolicy>;

// <<< CUSTOM
// END CUSTOM
