//! ContractTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the ContractTemplate CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CONTRACTTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for ContractTemplate
pub struct ContractTemplateTestData;

impl TestDataGenerator for ContractTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "contract_type": "pkwtt",
            "body_template": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "contract_type": "pkwtt",
            "body_template": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CONTRACTTEMPLATE API TEST
// ============================================================================

/// ContractTemplate API test suite
pub struct ContractTemplateApiTest {
    inner: GenericCrudTest<ContractTemplateTestData>,
}

impl ContractTemplateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/contract_templates", "ContractTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ContractTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ContractTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_contract_template_crud() {
        let mut test = ContractTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add ContractTemplate specific tests here
// <<< CUSTOM TESTS END >>>
