//! Contract API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Contract CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// CONTRACT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Contract
pub struct ContractTestData;

impl TestDataGenerator for ContractTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employment_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "contract_type": "pkwtt",
            "contract_no": null,
            "start_date": Utc::now().format("%Y-%m-%d").to_string(),
            "end_date": null,
            "status": "active",
            "document_file_id": null,
            "template_id": null,
            "previous_contract_id": null,
            "cumulative_pkwt_months": 1,
            "reminder_sent_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employment_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "contract_type": "pkwtt",
            "contract_no": null,
            "start_date": Utc::now().format("%Y-%m-%d").to_string(),
            "end_date": null,
            "status": "active",
            "document_file_id": null,
            "template_id": null,
            "previous_contract_id": null,
            "cumulative_pkwt_months": 1,
            "reminder_sent_at": now,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// CONTRACT API TEST
// ============================================================================

/// Contract API test suite
pub struct ContractApiTest {
    inner: GenericCrudTest<ContractTestData>,
}

impl ContractApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/contracts", "Contract");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, ContractTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for ContractApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_contract_crud() {
        let mut test = ContractApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Contract specific tests here
// <<< CUSTOM TESTS END >>>
