//! DisciplineRecord API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the DisciplineRecord CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// DISCIPLINERECORD TEST DATA GENERATOR
// ============================================================================

/// Test data generator for DisciplineRecord
pub struct DisciplineRecordTestData;

impl TestDataGenerator for DisciplineRecordTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "level": "sp1",
            "offense": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "issued_at": now,
            "valid_until": now,
            "served_disposition": "delivered",
            "status": "issued",
            "acknowledged_at": now,
            "acknowledged_via": null,
            "document_file_id": null,
            "cancel_reason": null,
            "prior_active_sp1": 1,
            "prior_active_sp2": 1,
            "issued_by": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "employee_id": Uuid::new_v4().to_string(),
            "level": "sp1",
            "offense": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "issued_at": now,
            "valid_until": now,
            "served_disposition": "delivered",
            "status": "issued",
            "acknowledged_at": now,
            "acknowledged_via": null,
            "document_file_id": null,
            "cancel_reason": null,
            "prior_active_sp1": 1,
            "prior_active_sp2": 1,
            "issued_by": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// DISCIPLINERECORD API TEST
// ============================================================================

/// DisciplineRecord API test suite
pub struct DisciplineRecordApiTest {
    inner: GenericCrudTest<DisciplineRecordTestData>,
}

impl DisciplineRecordApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/discipline_records", "DisciplineRecord");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, DisciplineRecordTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for DisciplineRecordApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_discipline_record_crud() {
        let mut test = DisciplineRecordApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add DisciplineRecord specific tests here
// <<< CUSTOM TESTS END >>>
