//! FinalSettlement API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the FinalSettlement CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// FINALSETTLEMENT TEST DATA GENERATOR
// ============================================================================

/// Test data generator for FinalSettlement
pub struct FinalSettlementTestData;

impl TestDataGenerator for FinalSettlementTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "offboarding_id": Uuid::new_v4().to_string(),
            "period": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "base_pay": 0,
            "unused_leave_payout": null,
            "pesangon_amount": null,
            "tax_deduction": null,
            "net_payable": 0,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "offboarding_id": Uuid::new_v4().to_string(),
            "period": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "base_pay": 0,
            "unused_leave_payout": null,
            "pesangon_amount": null,
            "tax_deduction": null,
            "net_payable": 0,
            "status": "draft",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/offboardings", &super::offboarding_api_test::OffboardingTestData).await {
            deps.push(("offboarding_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// FINALSETTLEMENT API TEST
// ============================================================================

/// FinalSettlement API test suite
pub struct FinalSettlementApiTest {
    inner: GenericCrudTest<FinalSettlementTestData>,
}

impl FinalSettlementApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/final_settlements", "FinalSettlement");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, FinalSettlementTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for FinalSettlementApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_final_settlement_crud() {
        let mut test = FinalSettlementApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add FinalSettlement specific tests here
// <<< CUSTOM TESTS END >>>
