//! OnboardingTemplateTask API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OnboardingTemplateTask CRUD API endpoints.

use crate::integration::framework::ApiTest;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ONBOARDINGTEMPLATETASK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OnboardingTemplateTask
pub struct OnboardingTemplateTaskTestData;

impl TestDataGenerator for OnboardingTemplateTaskTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "template_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "category": null,
            "owner_role": null,
            "due_day_offset": 1,
            "ordinal": 1,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "template_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "category": null,
            "owner_role": null,
            "due_day_offset": 1,
            "ordinal": 1,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/onboarding_templates", &super::onboarding_template_api_test::OnboardingTemplateTestData).await {
            deps.push(("template_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ONBOARDINGTEMPLATETASK API TEST
// ============================================================================

/// OnboardingTemplateTask API test suite
pub struct OnboardingTemplateTaskApiTest {
    inner: GenericCrudTest<OnboardingTemplateTaskTestData>,
}

impl OnboardingTemplateTaskApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/onboarding_template_tasks", "OnboardingTemplateTask");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OnboardingTemplateTaskTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OnboardingTemplateTaskApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_onboarding_template_task_crud() {
        let mut test = OnboardingTemplateTaskApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OnboardingTemplateTask specific tests here
// <<< CUSTOM TESTS END >>>
