//! OnboardingTask API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OnboardingTask CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ONBOARDINGTASK TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OnboardingTask
pub struct OnboardingTaskTestData;

impl TestDataGenerator for OnboardingTaskTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "onboarding_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "category": null,
            "owner_employee_id": null,
            "due_date": null,
            "status": "pending",
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "onboarding_id": Uuid::new_v4().to_string(),
            "title": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "category": null,
            "owner_employee_id": null,
            "due_date": null,
            "status": "pending",
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/onboardings", &super::onboarding_api_test::OnboardingTestData).await {
            deps.push(("onboarding_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// ONBOARDINGTASK API TEST
// ============================================================================

/// OnboardingTask API test suite
pub struct OnboardingTaskApiTest {
    inner: GenericCrudTest<OnboardingTaskTestData>,
}

impl OnboardingTaskApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/onboarding_tasks", "OnboardingTask");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OnboardingTaskTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OnboardingTaskApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_onboarding_task_crud() {
        let mut test = OnboardingTaskApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OnboardingTask specific tests here
// <<< CUSTOM TESTS END >>>
