//! OnboardingTemplate API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the OnboardingTemplate CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// ONBOARDINGTEMPLATE TEST DATA GENERATOR
// ============================================================================

/// Test data generator for OnboardingTemplate
pub struct OnboardingTemplateTestData;

impl TestDataGenerator for OnboardingTemplateTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "is_default": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "is_default": false,
            "is_active": false,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// ONBOARDINGTEMPLATE API TEST
// ============================================================================

/// OnboardingTemplate API test suite
pub struct OnboardingTemplateApiTest {
    inner: GenericCrudTest<OnboardingTemplateTestData>,
}

impl OnboardingTemplateApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/onboarding_templates", "OnboardingTemplate");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, OnboardingTemplateTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for OnboardingTemplateApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_onboarding_template_crud() {
        let mut test = OnboardingTemplateApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add OnboardingTemplate specific tests here
// <<< CUSTOM TESTS END >>>
