//! Promotion API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Promotion CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// PROMOTION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Promotion
pub struct PromotionTestData;

impl TestDataGenerator for PromotionTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "promotion_type": "promotion",
            "position_id_from": null,
            "position_id_to": null,
            "level_id_from": null,
            "level_id_to": null,
            "department_id_from": null,
            "department_id_to": null,
            "proposed_salary": null,
            "effective_date": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "requested_by": null,
            "approved_by": null,
            "appraisal_id": null,
            "reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        let now = Utc::now().to_rfc3339();
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "employee_id": Uuid::new_v4().to_string(),
            "promotion_type": "promotion",
            "position_id_from": null,
            "position_id_to": null,
            "level_id_from": null,
            "level_id_to": null,
            "department_id_from": null,
            "department_id_to": null,
            "proposed_salary": null,
            "effective_date": Utc::now().format("%Y-%m-%d").to_string(),
            "status": "draft",
            "requested_by": null,
            "approved_by": null,
            "appraisal_id": null,
            "reason": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// PROMOTION API TEST
// ============================================================================

/// Promotion API test suite
pub struct PromotionApiTest {
    inner: GenericCrudTest<PromotionTestData>,
}

impl PromotionApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/promotions", "Promotion");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, PromotionTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for PromotionApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_promotion_crud() {
        let mut test = PromotionApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Promotion specific tests here
// <<< CUSTOM TESTS END >>>
