//! Lifecycle Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::ClearanceItemService;
use crate::application::service::ExitInterviewService;
use crate::application::service::FinalSettlementService;
use crate::application::service::OffboardingService;
use crate::application::service::OnboardingService;
use crate::application::service::OnboardingTaskService;
use crate::application::service::PromotionService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// ClearanceItem service
    pub clearance_item_service: Arc<ClearanceItemService>,
    /// ExitInterview service
    pub exit_interview_service: Arc<ExitInterviewService>,
    /// FinalSettlement service
    pub final_settlement_service: Arc<FinalSettlementService>,
    /// Offboarding service
    pub offboarding_service: Arc<OffboardingService>,
    /// Onboarding service
    pub onboarding_service: Arc<OnboardingService>,
    /// OnboardingTask service
    pub onboarding_task_service: Arc<OnboardingTaskService>,
    /// Promotion service
    pub promotion_service: Arc<PromotionService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        clearance_item_service: Arc<ClearanceItemService>,
        exit_interview_service: Arc<ExitInterviewService>,
        final_settlement_service: Arc<FinalSettlementService>,
        offboarding_service: Arc<OffboardingService>,
        onboarding_service: Arc<OnboardingService>,
        onboarding_task_service: Arc<OnboardingTaskService>,
        promotion_service: Arc<PromotionService>
    ) -> Self {
        Self {
            clearance_item_service,
            exit_interview_service,
            final_settlement_service,
            offboarding_service,
            onboarding_service,
            onboarding_task_service,
            promotion_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::LifecycleModule) -> Self {
        Self {
            clearance_item_service: module.clearance_item_service.clone(),
            exit_interview_service: module.exit_interview_service.clone(),
            final_settlement_service: module.final_settlement_service.clone(),
            offboarding_service: module.offboarding_service.clone(),
            onboarding_service: module.onboarding_service.clone(),
            onboarding_task_service: module.onboarding_task_service.clone(),
            promotion_service: module.promotion_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    clearance_item_service: Option<Arc<ClearanceItemService>>,
    exit_interview_service: Option<Arc<ExitInterviewService>>,
    final_settlement_service: Option<Arc<FinalSettlementService>>,
    offboarding_service: Option<Arc<OffboardingService>>,
    onboarding_service: Option<Arc<OnboardingService>>,
    onboarding_task_service: Option<Arc<OnboardingTaskService>>,
    promotion_service: Option<Arc<PromotionService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the ClearanceItem service.
    pub fn with_clearance_item_service(mut self, service: Arc<ClearanceItemService>) -> Self {
        self.clearance_item_service = Some(service);
        self
    }

    /// Set the ExitInterview service.
    pub fn with_exit_interview_service(mut self, service: Arc<ExitInterviewService>) -> Self {
        self.exit_interview_service = Some(service);
        self
    }

    /// Set the FinalSettlement service.
    pub fn with_final_settlement_service(mut self, service: Arc<FinalSettlementService>) -> Self {
        self.final_settlement_service = Some(service);
        self
    }

    /// Set the Offboarding service.
    pub fn with_offboarding_service(mut self, service: Arc<OffboardingService>) -> Self {
        self.offboarding_service = Some(service);
        self
    }

    /// Set the Onboarding service.
    pub fn with_onboarding_service(mut self, service: Arc<OnboardingService>) -> Self {
        self.onboarding_service = Some(service);
        self
    }

    /// Set the OnboardingTask service.
    pub fn with_onboarding_task_service(mut self, service: Arc<OnboardingTaskService>) -> Self {
        self.onboarding_task_service = Some(service);
        self
    }

    /// Set the Promotion service.
    pub fn with_promotion_service(mut self, service: Arc<PromotionService>) -> Self {
        self.promotion_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            clearance_item_service: self.clearance_item_service.expect("clearance_item_service is required"),
            exit_interview_service: self.exit_interview_service.expect("exit_interview_service is required"),
            final_settlement_service: self.final_settlement_service.expect("final_settlement_service is required"),
            offboarding_service: self.offboarding_service.expect("offboarding_service is required"),
            onboarding_service: self.onboarding_service.expect("onboarding_service is required"),
            onboarding_task_service: self.onboarding_task_service.expect("onboarding_task_service is required"),
            promotion_service: self.promotion_service.expect("promotion_service is required"),
        }
    }
}
