//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    clearance_item_handler::create_clearance_item_routes,
    exit_interview_handler::create_exit_interview_routes,
    final_settlement_handler::create_final_settlement_routes,
    offboarding_handler::create_offboarding_routes,
    onboarding_handler::create_onboarding_routes,
    onboarding_task_handler::create_onboarding_task_routes,
    promotion_handler::create_promotion_routes,
};

use crate::application::service::{
    ClearanceItemService,
    ExitInterviewService,
    FinalSettlementService,
    OffboardingService,
    OnboardingService,
    OnboardingTaskService,
    PromotionService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub clearance_item: Arc<ClearanceItemService>,
    pub exit_interview: Arc<ExitInterviewService>,
    pub final_settlement: Arc<FinalSettlementService>,
    pub offboarding: Arc<OffboardingService>,
    pub onboarding: Arc<OnboardingService>,
    pub onboarding_task: Arc<OnboardingTaskService>,
    pub promotion: Arc<PromotionService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // ClearanceItem routes (12 Backbone endpoints)
        .merge(create_clearance_item_routes(services.clearance_item))
        // ExitInterview routes (12 Backbone endpoints)
        .merge(create_exit_interview_routes(services.exit_interview))
        // FinalSettlement routes (12 Backbone endpoints)
        .merge(create_final_settlement_routes(services.final_settlement))
        // Offboarding routes (12 Backbone endpoints)
        .merge(create_offboarding_routes(services.offboarding))
        // Onboarding routes (12 Backbone endpoints)
        .merge(create_onboarding_routes(services.onboarding))
        // OnboardingTask routes (12 Backbone endpoints)
        .merge(create_onboarding_task_routes(services.onboarding_task))
        // Promotion routes (12 Backbone endpoints)
        .merge(create_promotion_routes(services.promotion))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn clearance_item_routes(service: Arc<ClearanceItemService>) -> Router {
        create_clearance_item_routes(service)
    }

    pub fn exit_interview_routes(service: Arc<ExitInterviewService>) -> Router {
        create_exit_interview_routes(service)
    }

    pub fn final_settlement_routes(service: Arc<FinalSettlementService>) -> Router {
        create_final_settlement_routes(service)
    }

    pub fn offboarding_routes(service: Arc<OffboardingService>) -> Router {
        create_offboarding_routes(service)
    }

    pub fn onboarding_routes(service: Arc<OnboardingService>) -> Router {
        create_onboarding_routes(service)
    }

    pub fn onboarding_task_routes(service: Arc<OnboardingTaskService>) -> Router {
        create_onboarding_task_routes(service)
    }

    pub fn promotion_routes(service: Arc<PromotionService>) -> Router {
        create_promotion_routes(service)
    }

}
