//! Public events for Lifecycle module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// CLEARANCEITEM EVENTS
// ============================================================================

/// Event published when a ClearanceItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemCreatedEvent {
    pub id: ClearanceItemId,
    pub data: ClearanceItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ClearanceItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemUpdatedEvent {
    pub id: ClearanceItemId,
    pub data: ClearanceItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ClearanceItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemDeletedEvent {
    pub id: ClearanceItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EXITINTERVIEW EVENTS
// ============================================================================

/// Event published when a ExitInterview is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewCreatedEvent {
    pub id: ExitInterviewId,
    pub data: ExitInterviewDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExitInterview is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewUpdatedEvent {
    pub id: ExitInterviewId,
    pub data: ExitInterviewDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExitInterview is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewDeletedEvent {
    pub id: ExitInterviewId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// FINALSETTLEMENT EVENTS
// ============================================================================

/// Event published when a FinalSettlement is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementCreatedEvent {
    pub id: FinalSettlementId,
    pub data: FinalSettlementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a FinalSettlement is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementUpdatedEvent {
    pub id: FinalSettlementId,
    pub data: FinalSettlementDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a FinalSettlement is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementDeletedEvent {
    pub id: FinalSettlementId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// OFFBOARDING EVENTS
// ============================================================================

/// Event published when a Offboarding is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingCreatedEvent {
    pub id: OffboardingId,
    pub data: OffboardingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Offboarding is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingUpdatedEvent {
    pub id: OffboardingId,
    pub data: OffboardingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Offboarding is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingDeletedEvent {
    pub id: OffboardingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ONBOARDING EVENTS
// ============================================================================

/// Event published when a Onboarding is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingCreatedEvent {
    pub id: OnboardingId,
    pub data: OnboardingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Onboarding is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingUpdatedEvent {
    pub id: OnboardingId,
    pub data: OnboardingDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Onboarding is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingDeletedEvent {
    pub id: OnboardingId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// ONBOARDINGTASK EVENTS
// ============================================================================

/// Event published when a OnboardingTask is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskCreatedEvent {
    pub id: OnboardingTaskId,
    pub data: OnboardingTaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OnboardingTask is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskUpdatedEvent {
    pub id: OnboardingTaskId,
    pub data: OnboardingTaskDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a OnboardingTask is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskDeletedEvent {
    pub id: OnboardingTaskId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// PROMOTION EVENTS
// ============================================================================

/// Event published when a Promotion is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionCreatedEvent {
    pub id: PromotionId,
    pub data: PromotionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Promotion is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionUpdatedEvent {
    pub id: PromotionId,
    pub data: PromotionDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Promotion is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionDeletedEvent {
    pub id: PromotionId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Lifecycle module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum LifecycleEvent {
    ClearanceItemCreated(ClearanceItemCreatedEvent),
    ClearanceItemUpdated(ClearanceItemUpdatedEvent),
    ClearanceItemDeleted(ClearanceItemDeletedEvent),
    ExitInterviewCreated(ExitInterviewCreatedEvent),
    ExitInterviewUpdated(ExitInterviewUpdatedEvent),
    ExitInterviewDeleted(ExitInterviewDeletedEvent),
    FinalSettlementCreated(FinalSettlementCreatedEvent),
    FinalSettlementUpdated(FinalSettlementUpdatedEvent),
    FinalSettlementDeleted(FinalSettlementDeletedEvent),
    OffboardingCreated(OffboardingCreatedEvent),
    OffboardingUpdated(OffboardingUpdatedEvent),
    OffboardingDeleted(OffboardingDeletedEvent),
    OnboardingCreated(OnboardingCreatedEvent),
    OnboardingUpdated(OnboardingUpdatedEvent),
    OnboardingDeleted(OnboardingDeletedEvent),
    OnboardingTaskCreated(OnboardingTaskCreatedEvent),
    OnboardingTaskUpdated(OnboardingTaskUpdatedEvent),
    OnboardingTaskDeleted(OnboardingTaskDeletedEvent),
    PromotionCreated(PromotionCreatedEvent),
    PromotionUpdated(PromotionUpdatedEvent),
    PromotionDeleted(PromotionDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LifecycleEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for LifecycleEventMetadata {
    fn default() -> Self {
        Self {
            module: "lifecycle",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
