//! Public types for Lifecycle module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// CLEARANCEITEM TYPES
// ============================================================================

/// Type-safe ID for ClearanceItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ClearanceItemId(pub Uuid);

impl ClearanceItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ClearanceItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ClearanceItemId> for Uuid {
    fn from(id: ClearanceItemId) -> Self {
        id.0
    }
}

/// Data transfer object for ClearanceItem
///
/// This is the public representation of ClearanceItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemDto {
    pub id: ClearanceItemId,
    pub company_id: Uuid,
    pub offboarding_id: Uuid,
    pub title: String,
    pub clearer_employee_id: Option<Uuid>,
    pub status: ClearanceStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of ClearanceItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemSummary {
    pub id: ClearanceItemId,
    pub title: String,
    pub status: ClearanceStatus,
}

/// Reference to ClearanceItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClearanceItemRef {
    pub id: ClearanceItemId,
}

// ============================================================================
// EXITINTERVIEW TYPES
// ============================================================================

/// Type-safe ID for ExitInterview
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExitInterviewId(pub Uuid);

impl ExitInterviewId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ExitInterviewId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ExitInterviewId> for Uuid {
    fn from(id: ExitInterviewId) -> Self {
        id.0
    }
}

/// Data transfer object for ExitInterview
///
/// This is the public representation of ExitInterview for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewDto {
    pub id: ExitInterviewId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub offboarding_id: Option<Uuid>,
    pub conducted_by: Option<Uuid>,
    pub responses: serde_json::Value,
    pub would_recommend: Option<bool>,
    pub metadata: serde_json::Value,
}

/// Summary view of ExitInterview for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewSummary {
    pub id: ExitInterviewId,
}

/// Reference to ExitInterview for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitInterviewRef {
    pub id: ExitInterviewId,
}

// ============================================================================
// FINALSETTLEMENT TYPES
// ============================================================================

/// Type-safe ID for FinalSettlement
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct FinalSettlementId(pub Uuid);

impl FinalSettlementId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for FinalSettlementId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<FinalSettlementId> for Uuid {
    fn from(id: FinalSettlementId) -> Self {
        id.0
    }
}

/// Data transfer object for FinalSettlement
///
/// This is the public representation of FinalSettlement for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementDto {
    pub id: FinalSettlementId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub offboarding_id: Uuid,
    pub period: String,
    pub base_pay: Decimal,
    pub unused_leave_payout: Option<Decimal>,
    pub pesangon_amount: Option<Decimal>,
    pub tax_deduction: Option<Decimal>,
    pub net_payable: Decimal,
    pub status: SettlementStatus,
    pub accounting_post_id: Option<Uuid>,
    pub journal_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of FinalSettlement for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementSummary {
    pub id: FinalSettlementId,
    pub status: SettlementStatus,
}

/// Reference to FinalSettlement for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FinalSettlementRef {
    pub id: FinalSettlementId,
}

// ============================================================================
// OFFBOARDING TYPES
// ============================================================================

/// Type-safe ID for Offboarding
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OffboardingId(pub Uuid);

impl OffboardingId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OffboardingId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OffboardingId> for Uuid {
    fn from(id: OffboardingId) -> Self {
        id.0
    }
}

/// Data transfer object for Offboarding
///
/// This is the public representation of Offboarding for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingDto {
    pub id: OffboardingId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub reason: OffboardingReason,
    pub notice_date: NaiveDate,
    pub last_working_day: NaiveDate,
    pub status: OffboardingStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of Offboarding for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingSummary {
    pub id: OffboardingId,
    pub status: OffboardingStatus,
}

/// Reference to Offboarding for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OffboardingRef {
    pub id: OffboardingId,
}

// ============================================================================
// ONBOARDING TYPES
// ============================================================================

/// Type-safe ID for Onboarding
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OnboardingId(pub Uuid);

impl OnboardingId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OnboardingId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OnboardingId> for Uuid {
    fn from(id: OnboardingId) -> Self {
        id.0
    }
}

/// Data transfer object for Onboarding
///
/// This is the public representation of Onboarding for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingDto {
    pub id: OnboardingId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub start_date: NaiveDate,
    pub status: OnboardingStatus,
    pub completed_at: Option<DateTime<Utc>>,
    pub probation_end_date: Option<NaiveDate>,
    pub confirmed_at: Option<DateTime<Utc>>,
    pub template_id: Option<Uuid>,
    pub metadata: serde_json::Value,
}

/// Summary view of Onboarding for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingSummary {
    pub id: OnboardingId,
    pub status: OnboardingStatus,
}

/// Reference to Onboarding for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingRef {
    pub id: OnboardingId,
}

// ============================================================================
// ONBOARDINGTASK TYPES
// ============================================================================

/// Type-safe ID for OnboardingTask
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct OnboardingTaskId(pub Uuid);

impl OnboardingTaskId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for OnboardingTaskId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<OnboardingTaskId> for Uuid {
    fn from(id: OnboardingTaskId) -> Self {
        id.0
    }
}

/// Data transfer object for OnboardingTask
///
/// This is the public representation of OnboardingTask for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskDto {
    pub id: OnboardingTaskId,
    pub company_id: Uuid,
    pub onboarding_id: Uuid,
    pub title: String,
    pub category: Option<TaskCategory>,
    pub owner_employee_id: Option<Uuid>,
    pub due_date: Option<NaiveDate>,
    pub status: TaskStatus,
    pub metadata: serde_json::Value,
}

/// Summary view of OnboardingTask for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskSummary {
    pub id: OnboardingTaskId,
    pub title: String,
    pub status: TaskStatus,
}

/// Reference to OnboardingTask for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OnboardingTaskRef {
    pub id: OnboardingTaskId,
}

// ============================================================================
// PROMOTION TYPES
// ============================================================================

/// Type-safe ID for Promotion
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct PromotionId(pub Uuid);

impl PromotionId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for PromotionId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<PromotionId> for Uuid {
    fn from(id: PromotionId) -> Self {
        id.0
    }
}

/// Data transfer object for Promotion
///
/// This is the public representation of Promotion for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionDto {
    pub id: PromotionId,
    pub company_id: Uuid,
    pub employee_id: Uuid,
    pub promotion_type: PromotionType,
    pub position_id_from: Option<Uuid>,
    pub position_id_to: Option<Uuid>,
    pub level_id_from: Option<Uuid>,
    pub level_id_to: Option<Uuid>,
    pub department_id_from: Option<Uuid>,
    pub department_id_to: Option<Uuid>,
    pub proposed_salary: Option<Decimal>,
    pub effective_date: NaiveDate,
    pub status: PromotionStatus,
    pub requested_by: Option<Uuid>,
    pub approved_by: Option<Uuid>,
    pub appraisal_id: Option<Uuid>,
    pub reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Promotion for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionSummary {
    pub id: PromotionId,
    pub status: PromotionStatus,
}

/// Reference to Promotion for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromotionRef {
    pub id: PromotionId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
