//! Lifecycle Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;
pub mod exports;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::ClearanceItemService;
pub use application::service::ExitInterviewService;
pub use application::service::FinalSettlementService;
pub use application::service::OffboardingService;
pub use application::service::OnboardingService;
pub use application::service::OnboardingTaskService;
pub use application::service::PromotionService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Lifecycle module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let lifecycle = LifecycleModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = lifecycle.all_crud_routes();
/// ```
pub struct LifecycleModule {
    pub(crate) clearance_item_service: Arc<ClearanceItemService>,
    pub(crate) exit_interview_service: Arc<ExitInterviewService>,
    pub(crate) final_settlement_service: Arc<FinalSettlementService>,
    pub(crate) offboarding_service: Arc<OffboardingService>,
    pub(crate) onboarding_service: Arc<OnboardingService>,
    pub(crate) onboarding_task_service: Arc<OnboardingTaskService>,
    pub(crate) promotion_service: Arc<PromotionService>,
    // <<< CUSTOM FIELDS
    /// The three career-lifecycle write-services (ADR-005 producers): each flips a workflow status
    /// and stages the matching compound event in one tx. Public so the composer / tests can drive
    /// them (`module.promotion_write_service.effect(id)`, etc.).
    pub promotion_write_service: Arc<application::service::PromotionWriteService>,
    pub onboarding_write_service: Arc<application::service::OnboardingWriteService>,
    pub offboarding_write_service: Arc<application::service::OffboardingWriteService>,
    // END CUSTOM
}

impl LifecycleModule {
    /// Create a new module builder
    pub fn builder() -> LifecycleModuleBuilder {
        LifecycleModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_clearance_item_routes,
            create_exit_interview_routes,
            create_final_settlement_routes,
            create_offboarding_routes,
            create_onboarding_routes,
            create_onboarding_task_routes,
            create_promotion_routes,
        };

        Router::new()
            .merge(create_clearance_item_routes(self.clearance_item_service.clone()))
            .merge(create_exit_interview_routes(self.exit_interview_service.clone()))
            .merge(create_final_settlement_routes(self.final_settlement_service.clone()))
            .merge(create_offboarding_routes(self.offboarding_service.clone()))
            .merge(create_onboarding_routes(self.onboarding_service.clone()))
            .merge(create_onboarding_task_routes(self.onboarding_task_service.clone()))
            .merge(create_promotion_routes(self.promotion_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for LifecycleModule
pub struct LifecycleModuleBuilder {
    db_pool: Option<PgPool>,
    // <<< CUSTOM
    // ADR-005 offboarding producer: optional overrides for the pesangon input port + config. When
    // unset, build() falls back to a pool-backed OffboardingInputs and PesangonConfig::default()
    // (current-law 🇮🇩 rates) — so the composer's `with_database(pool).build()` keeps working
    // unchanged, while a deployment that loads rates from application.yml or injects a
    // module-backed inputs impl can do so explicitly.
    offboarding_inputs: Option<Arc<dyn application::service::OffboardingInputs>>,
    pesangon_config: Option<application::service::PesangonConfig>,
    // END CUSTOM
}

impl LifecycleModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
            // <<< CUSTOM
            offboarding_inputs: None,
            pesangon_config: None,
            // END CUSTOM
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    /// Override the cross-module read port the offboarding producer uses to gather the pesangon
    /// inputs (join_date / current salary / remaining leave). Defaults to a pool-backed impl that
    /// reads `employee.employments` / `payroll.compensation_changes` / `timeoff.timeoff_balances`
    /// directly — only override if you need a different read source.
    pub fn with_offboarding_inputs(mut self, inputs: Arc<dyn application::service::OffboardingInputs>) -> Self {
        self.offboarding_inputs = Some(inputs);
        self
    }

    /// Override the pesangon config (rates/scale/rules). Defaults to [`PesangonConfig::default`]
    /// (current-law 🇮🇩 values); pass a YAML-loaded config to honor `config/application.yml`.
    pub fn with_pesangon_config(mut self, cfg: application::service::PesangonConfig) -> Self {
        self.pesangon_config = Some(cfg);
        self
    }
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<LifecycleModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // ClearanceItem service
        let clearance_item_repository = Arc::new(ClearanceItemRepository::new(db_pool.clone()));
        let clearance_item_service = Arc::new(ClearanceItemService::with_repository(clearance_item_repository.clone()));

        // ExitInterview service
        let exit_interview_repository = Arc::new(ExitInterviewRepository::new(db_pool.clone()));
        let exit_interview_service = Arc::new(ExitInterviewService::with_repository(exit_interview_repository.clone()));

        // FinalSettlement service
        let final_settlement_repository = Arc::new(FinalSettlementRepository::new(db_pool.clone()));
        let final_settlement_service = Arc::new(FinalSettlementService::with_repository(final_settlement_repository.clone()));

        // Offboarding service
        let offboarding_repository = Arc::new(OffboardingRepository::new(db_pool.clone()));
        let offboarding_service = Arc::new(OffboardingService::with_repository(offboarding_repository.clone()));

        // Onboarding service
        let onboarding_repository = Arc::new(OnboardingRepository::new(db_pool.clone()));
        let onboarding_service = Arc::new(OnboardingService::with_repository(onboarding_repository.clone()));

        // OnboardingTask service
        let onboarding_task_repository = Arc::new(OnboardingTaskRepository::new(db_pool.clone()));
        let onboarding_task_service = Arc::new(OnboardingTaskService::with_repository(onboarding_task_repository.clone()));

        // Promotion service
        let promotion_repository = Arc::new(PromotionRepository::new(db_pool.clone()));
        let promotion_service = Arc::new(PromotionService::with_repository(promotion_repository.clone()));

        // <<< CUSTOM
        // ADR-005 producers: bound to the same pool as the repos. Each verb opens its own tx around
        // the state change + the outbox stage; no shared mutable state, so an Arc is purely for cheap reuse.
        let promotion_write_service = Arc::new(application::service::PromotionWriteService::new(db_pool.clone()));
        let onboarding_write_service = Arc::new(application::service::OnboardingWriteService::new(db_pool.clone()));
        // The offboarding producer also computes the 🇮🇩 pesangon, so it needs the cross-module
        // inputs port + the pesangon config. Fall back to pool-backed inputs + current-law config
        // when the builder didn't override them.
        let offboarding_inputs = self.offboarding_inputs.unwrap_or_else(|| {
            Arc::new(application::service::PoolOffboardingInputs::new(db_pool.clone()))
        });
        let pesangon_config = self.pesangon_config.unwrap_or_default();
        let offboarding_write_service = Arc::new(application::service::OffboardingWriteService::new(
            db_pool.clone(),
            offboarding_inputs,
            pesangon_config,
        ));
        // END CUSTOM

        Ok(LifecycleModule {
            clearance_item_service,
            exit_interview_service,
            final_settlement_service,
            offboarding_service,
            onboarding_service,
            onboarding_task_service,
            promotion_service,
            // <<< CUSTOM
            promotion_write_service,
            onboarding_write_service,
            offboarding_write_service,
            // END CUSTOM
        })
    }
}

impl Default for LifecycleModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
