//! Use case type aliases for ClearanceItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateClearanceItemDto, UpdateClearanceItemDto};
use crate::application::service::ClearanceItemService;
use crate::domain::entity::ClearanceItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateClearanceItemUseCase = CreateUseCase<ClearanceItem, CreateClearanceItemDto, ClearanceItemService>;
pub type UpdateClearanceItemUseCase = UpdateUseCase<ClearanceItem, UpdateClearanceItemDto, ClearanceItemService>;
pub type GetClearanceItemUseCase    = GetUseCase<ClearanceItem, ClearanceItemService>;
pub type DeleteClearanceItemUseCase = DeleteUseCase<ClearanceItem, ClearanceItemService>;
pub type ListClearanceItemUseCase   = ListUseCase<ClearanceItem, ClearanceItemService>;

// <<< CUSTOM
// END CUSTOM
