//! Use case type aliases for ExitInterview aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateExitInterviewDto, UpdateExitInterviewDto};
use crate::application::service::ExitInterviewService;
use crate::domain::entity::ExitInterview;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateExitInterviewUseCase = CreateUseCase<ExitInterview, CreateExitInterviewDto, ExitInterviewService>;
pub type UpdateExitInterviewUseCase = UpdateUseCase<ExitInterview, UpdateExitInterviewDto, ExitInterviewService>;
pub type GetExitInterviewUseCase    = GetUseCase<ExitInterview, ExitInterviewService>;
pub type DeleteExitInterviewUseCase = DeleteUseCase<ExitInterview, ExitInterviewService>;
pub type ListExitInterviewUseCase   = ListUseCase<ExitInterview, ExitInterviewService>;

// <<< CUSTOM
// END CUSTOM
