//! Use case type aliases for FinalSettlement aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateFinalSettlementDto, UpdateFinalSettlementDto};
use crate::application::service::FinalSettlementService;
use crate::domain::entity::FinalSettlement;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateFinalSettlementUseCase = CreateUseCase<FinalSettlement, CreateFinalSettlementDto, FinalSettlementService>;
pub type UpdateFinalSettlementUseCase = UpdateUseCase<FinalSettlement, UpdateFinalSettlementDto, FinalSettlementService>;
pub type GetFinalSettlementUseCase    = GetUseCase<FinalSettlement, FinalSettlementService>;
pub type DeleteFinalSettlementUseCase = DeleteUseCase<FinalSettlement, FinalSettlementService>;
pub type ListFinalSettlementUseCase   = ListUseCase<FinalSettlement, FinalSettlementService>;

// <<< CUSTOM
// END CUSTOM
