//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod clearance_item_usecases;
pub mod exit_interview_usecases;
pub mod final_settlement_usecases;
pub mod offboarding_usecases;
pub mod onboarding_usecases;
pub mod onboarding_task_usecases;
pub mod promotion_usecases;

pub use clearance_item_usecases::{
    CreateClearanceItemUseCase, UpdateClearanceItemUseCase, GetClearanceItemUseCase,
    DeleteClearanceItemUseCase, ListClearanceItemUseCase,
};
pub use exit_interview_usecases::{
    CreateExitInterviewUseCase, UpdateExitInterviewUseCase, GetExitInterviewUseCase,
    DeleteExitInterviewUseCase, ListExitInterviewUseCase,
};
pub use final_settlement_usecases::{
    CreateFinalSettlementUseCase, UpdateFinalSettlementUseCase, GetFinalSettlementUseCase,
    DeleteFinalSettlementUseCase, ListFinalSettlementUseCase,
};
pub use offboarding_usecases::{
    CreateOffboardingUseCase, UpdateOffboardingUseCase, GetOffboardingUseCase,
    DeleteOffboardingUseCase, ListOffboardingUseCase,
};
pub use onboarding_usecases::{
    CreateOnboardingUseCase, UpdateOnboardingUseCase, GetOnboardingUseCase,
    DeleteOnboardingUseCase, ListOnboardingUseCase,
};
pub use onboarding_task_usecases::{
    CreateOnboardingTaskUseCase, UpdateOnboardingTaskUseCase, GetOnboardingTaskUseCase,
    DeleteOnboardingTaskUseCase, ListOnboardingTaskUseCase,
};
pub use promotion_usecases::{
    CreatePromotionUseCase, UpdatePromotionUseCase, GetPromotionUseCase,
    DeletePromotionUseCase, ListPromotionUseCase,
};

// <<< CUSTOM
// END CUSTOM
