//! Use case type aliases for Onboarding aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOnboardingDto, UpdateOnboardingDto};
use crate::application::service::OnboardingService;
use crate::domain::entity::Onboarding;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOnboardingUseCase = CreateUseCase<Onboarding, CreateOnboardingDto, OnboardingService>;
pub type UpdateOnboardingUseCase = UpdateUseCase<Onboarding, UpdateOnboardingDto, OnboardingService>;
pub type GetOnboardingUseCase    = GetUseCase<Onboarding, OnboardingService>;
pub type DeleteOnboardingUseCase = DeleteUseCase<Onboarding, OnboardingService>;
pub type ListOnboardingUseCase   = ListUseCase<Onboarding, OnboardingService>;

// <<< CUSTOM
// END CUSTOM
