//! Use case type aliases for OnboardingTask aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateOnboardingTaskDto, UpdateOnboardingTaskDto};
use crate::application::service::OnboardingTaskService;
use crate::domain::entity::OnboardingTask;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateOnboardingTaskUseCase = CreateUseCase<OnboardingTask, CreateOnboardingTaskDto, OnboardingTaskService>;
pub type UpdateOnboardingTaskUseCase = UpdateUseCase<OnboardingTask, UpdateOnboardingTaskDto, OnboardingTaskService>;
pub type GetOnboardingTaskUseCase    = GetUseCase<OnboardingTask, OnboardingTaskService>;
pub type DeleteOnboardingTaskUseCase = DeleteUseCase<OnboardingTask, OnboardingTaskService>;
pub type ListOnboardingTaskUseCase   = ListUseCase<OnboardingTask, OnboardingTaskService>;

// <<< CUSTOM
// END CUSTOM
