//! Use case type aliases for Promotion aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreatePromotionDto, UpdatePromotionDto};
use crate::application::service::PromotionService;
use crate::domain::entity::Promotion;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreatePromotionUseCase = CreateUseCase<Promotion, CreatePromotionDto, PromotionService>;
pub type UpdatePromotionUseCase = UpdateUseCase<Promotion, UpdatePromotionDto, PromotionService>;
pub type GetPromotionUseCase    = GetUseCase<Promotion, PromotionService>;
pub type DeletePromotionUseCase = DeleteUseCase<Promotion, PromotionService>;
pub type ListPromotionUseCase   = ListUseCase<Promotion, PromotionService>;

// <<< CUSTOM
// END CUSTOM
