//! HTTP handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These handlers use Axum and backbone-core's BackboneCrudHandler
//! to provide all 12 standard Backbone CRUD endpoints.

pub mod clearance_item_handler;
pub mod exit_interview_handler;
pub mod final_settlement_handler;
pub mod offboarding_handler;
pub mod onboarding_handler;
pub mod onboarding_task_handler;
pub mod promotion_handler;

// <<< CUSTOM
// END CUSTOM

// Re-exports
pub use clearance_item_handler::{create_clearance_item_routes, create_clearance_item_read_routes, create_clearance_item_write_routes};
pub use exit_interview_handler::{create_exit_interview_routes, create_exit_interview_read_routes, create_exit_interview_write_routes};
pub use final_settlement_handler::{create_final_settlement_routes, create_final_settlement_read_routes, create_final_settlement_write_routes};
pub use offboarding_handler::{create_offboarding_routes, create_offboarding_read_routes, create_offboarding_write_routes};
pub use onboarding_handler::{create_onboarding_routes, create_onboarding_read_routes, create_onboarding_write_routes};
pub use onboarding_task_handler::{create_onboarding_task_routes, create_onboarding_task_read_routes, create_onboarding_task_write_routes};
pub use promotion_handler::{create_promotion_routes, create_promotion_read_routes, create_promotion_write_routes};
// <<< CUSTOM
// END CUSTOM
